/*
 * Eleoncore API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleoncoreProxy.Model;
using EleoncoreProxy.Client;
using System.Reflection;

namespace EleoncoreProxy.Test.Model
{
    /// <summary>
    ///  Class for testing EleoncoreControllerApiDescriptionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EleoncoreControllerApiDescriptionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EleoncoreControllerApiDescriptionModel
        //private EleoncoreControllerApiDescriptionModel instance;

        public EleoncoreControllerApiDescriptionModelTests()
        {
            // TODO uncomment below to create an instance of EleoncoreControllerApiDescriptionModel
            //instance = new EleoncoreControllerApiDescriptionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EleoncoreControllerApiDescriptionModel
        /// </summary>
        [Fact]
        public void EleoncoreControllerApiDescriptionModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" EleoncoreControllerApiDescriptionModel
            //Assert.IsType<EleoncoreControllerApiDescriptionModel>(instance);
        }

        /// <summary>
        /// Test the property 'ControllerName'
        /// </summary>
        [Fact]
        public void ControllerNameTest()
        {
            // TODO unit test for the property 'ControllerName'
        }

        /// <summary>
        /// Test the property 'ControllerGroupName'
        /// </summary>
        [Fact]
        public void ControllerGroupNameTest()
        {
            // TODO unit test for the property 'ControllerGroupName'
        }

        /// <summary>
        /// Test the property 'IsRemoteService'
        /// </summary>
        [Fact]
        public void IsRemoteServiceTest()
        {
            // TODO unit test for the property 'IsRemoteService'
        }

        /// <summary>
        /// Test the property 'IsIntegrationService'
        /// </summary>
        [Fact]
        public void IsIntegrationServiceTest()
        {
            // TODO unit test for the property 'IsIntegrationService'
        }

        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Fact]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Interfaces'
        /// </summary>
        [Fact]
        public void InterfacesTest()
        {
            // TODO unit test for the property 'Interfaces'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
    }
}
