// <auto-generated>
/*
 * Eleoncore API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleoncoreProxy.Client;

namespace EleoncoreProxy.Model
{
    /// <summary>
    /// EleoncoreTypeApiDescriptionModel
    /// </summary>
    public partial class EleoncoreTypeApiDescriptionModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EleoncoreTypeApiDescriptionModel" /> class.
        /// </summary>
        /// <param name="baseType">baseType</param>
        /// <param name="isEnum">isEnum</param>
        /// <param name="enumNames">enumNames</param>
        /// <param name="enumValues">enumValues</param>
        /// <param name="genericArguments">genericArguments</param>
        /// <param name="properties">properties</param>
        [JsonConstructor]
        public EleoncoreTypeApiDescriptionModel(Option<string> baseType = default, Option<bool?> isEnum = default, Option<List<string>> enumNames = default, Option<List<Object>> enumValues = default, Option<List<string>> genericArguments = default, Option<List<EleoncorePropertyApiDescriptionModel>> properties = default)
        {
            BaseTypeOption = baseType;
            IsEnumOption = isEnum;
            EnumNamesOption = enumNames;
            EnumValuesOption = enumValues;
            GenericArgumentsOption = genericArguments;
            PropertiesOption = properties;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of BaseType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> BaseTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets BaseType
        /// </summary>
        [JsonPropertyName("baseType")]
        public string BaseType { get { return this.BaseTypeOption; } set { this.BaseTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsEnum
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsEnumOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsEnum
        /// </summary>
        [JsonPropertyName("isEnum")]
        public bool? IsEnum { get { return this.IsEnumOption; } set { this.IsEnumOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnumNames
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> EnumNamesOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnumNames
        /// </summary>
        [JsonPropertyName("enumNames")]
        public List<string> EnumNames { get { return this.EnumNamesOption; } set { this.EnumNamesOption = new(value); } }

        /// <summary>
        /// Used to track the state of EnumValues
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Object>> EnumValuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets EnumValues
        /// </summary>
        [JsonPropertyName("enumValues")]
        public List<Object> EnumValues { get { return this.EnumValuesOption; } set { this.EnumValuesOption = new(value); } }

        /// <summary>
        /// Used to track the state of GenericArguments
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> GenericArgumentsOption { get; private set; }

        /// <summary>
        /// Gets or Sets GenericArguments
        /// </summary>
        [JsonPropertyName("genericArguments")]
        public List<string> GenericArguments { get { return this.GenericArgumentsOption; } set { this.GenericArgumentsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Properties
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EleoncorePropertyApiDescriptionModel>> PropertiesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Properties
        /// </summary>
        [JsonPropertyName("properties")]
        public List<EleoncorePropertyApiDescriptionModel> Properties { get { return this.PropertiesOption; } set { this.PropertiesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EleoncoreTypeApiDescriptionModel {\n");
            sb.Append("  BaseType: ").Append(BaseType).Append("\n");
            sb.Append("  IsEnum: ").Append(IsEnum).Append("\n");
            sb.Append("  EnumNames: ").Append(EnumNames).Append("\n");
            sb.Append("  EnumValues: ").Append(EnumValues).Append("\n");
            sb.Append("  GenericArguments: ").Append(GenericArguments).Append("\n");
            sb.Append("  Properties: ").Append(Properties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreTypeApiDescriptionModel" />
    /// </summary>
    public class EleoncoreTypeApiDescriptionModelJsonConverter : JsonConverter<EleoncoreTypeApiDescriptionModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="EleoncoreTypeApiDescriptionModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EleoncoreTypeApiDescriptionModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> baseType = default;
            Option<bool?> isEnum = default;
            Option<List<string>> enumNames = default;
            Option<List<Object>> enumValues = default;
            Option<List<string>> genericArguments = default;
            Option<List<EleoncorePropertyApiDescriptionModel>> properties = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "baseType":
                            baseType = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "isEnum":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isEnum = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "enumNames":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enumNames = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "enumValues":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                enumValues = new Option<List<Object>>(JsonSerializer.Deserialize<List<Object>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "genericArguments":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                genericArguments = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "properties":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                properties = new Option<List<EleoncorePropertyApiDescriptionModel>>(JsonSerializer.Deserialize<List<EleoncorePropertyApiDescriptionModel>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (isEnum.IsSet && isEnum.Value == null)
                throw new ArgumentNullException(nameof(isEnum), "Property is not nullable for class EleoncoreTypeApiDescriptionModel.");

            return new EleoncoreTypeApiDescriptionModel(baseType, isEnum, enumNames, enumValues, genericArguments, properties);
        }

        /// <summary>
        /// Serializes a <see cref="EleoncoreTypeApiDescriptionModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreTypeApiDescriptionModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EleoncoreTypeApiDescriptionModel eleoncoreTypeApiDescriptionModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eleoncoreTypeApiDescriptionModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EleoncoreTypeApiDescriptionModel" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eleoncoreTypeApiDescriptionModel"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EleoncoreTypeApiDescriptionModel eleoncoreTypeApiDescriptionModel, JsonSerializerOptions jsonSerializerOptions)
{
    if (eleoncoreTypeApiDescriptionModel.BaseTypeOption.IsSet)
    {
        if (eleoncoreTypeApiDescriptionModel.BaseTypeOption.Value != null)
        {
            writer.WritePropertyName("baseType");
            JsonSerializer.Serialize(writer, eleoncoreTypeApiDescriptionModel.BaseType, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("baseType");
        }
    }
    if (eleoncoreTypeApiDescriptionModel.IsEnumOption.IsSet)
    {
        writer.WritePropertyName("isEnum");
        JsonSerializer.Serialize(writer, eleoncoreTypeApiDescriptionModel.IsEnum, jsonSerializerOptions);
    }
    if (eleoncoreTypeApiDescriptionModel.EnumNamesOption.IsSet)
    {
        if (eleoncoreTypeApiDescriptionModel.EnumNamesOption.Value != null)
        {
            writer.WritePropertyName("enumNames");
            JsonSerializer.Serialize(writer, eleoncoreTypeApiDescriptionModel.EnumNames, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("enumNames");
        }
    }
    if (eleoncoreTypeApiDescriptionModel.EnumValuesOption.IsSet)
    {
        if (eleoncoreTypeApiDescriptionModel.EnumValuesOption.Value != null)
        {
            writer.WritePropertyName("enumValues");
            JsonSerializer.Serialize(writer, eleoncoreTypeApiDescriptionModel.EnumValues, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("enumValues");
        }
    }
    if (eleoncoreTypeApiDescriptionModel.GenericArgumentsOption.IsSet)
    {
        if (eleoncoreTypeApiDescriptionModel.GenericArgumentsOption.Value != null)
        {
            writer.WritePropertyName("genericArguments");
            JsonSerializer.Serialize(writer, eleoncoreTypeApiDescriptionModel.GenericArguments, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("genericArguments");
        }
    }
    if (eleoncoreTypeApiDescriptionModel.PropertiesOption.IsSet)
    {
        if (eleoncoreTypeApiDescriptionModel.PropertiesOption.Value != null)
        {
            writer.WritePropertyName("properties");
            JsonSerializer.Serialize(writer, eleoncoreTypeApiDescriptionModel.Properties, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("properties");
        }
    }
}

    }
}
