// <auto-generated>
/*
 * Eleoncore API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleoncoreProxy.Client;

namespace EleoncoreProxy.Model
{
    /// <summary>
    /// EleoncoreReturnValueApiDescriptionModel
    /// </summary>
    public partial class EleoncoreReturnValueApiDescriptionModel : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EleoncoreReturnValueApiDescriptionModel" /> class.
        /// </summary>
        /// <param name="type">type</param>
        /// <param name="typeSimple">typeSimple</param>
        [JsonConstructor]
        public EleoncoreReturnValueApiDescriptionModel(Option<string> type = default, Option<string> typeSimple = default)
        {
            TypeOption = type;
            TypeSimpleOption = typeSimple;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of TypeSimple
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TypeSimpleOption { get; private set; }

        /// <summary>
        /// Gets or Sets TypeSimple
        /// </summary>
        [JsonPropertyName("typeSimple")]
        public string TypeSimple { get { return this.TypeSimpleOption; } set { this.TypeSimpleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EleoncoreReturnValueApiDescriptionModel {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  TypeSimple: ").Append(TypeSimple).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreReturnValueApiDescriptionModel" />
    /// </summary>
    public class EleoncoreReturnValueApiDescriptionModelJsonConverter : JsonConverter<EleoncoreReturnValueApiDescriptionModel>
    {
        /// <summary>
        /// Deserializes json to <see cref="EleoncoreReturnValueApiDescriptionModel" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EleoncoreReturnValueApiDescriptionModel Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> type = default;
            Option<string> typeSimple = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "type":
                            type = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "typeSimple":
                            typeSimple = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            return new EleoncoreReturnValueApiDescriptionModel(type, typeSimple);
        }

        /// <summary>
        /// Serializes a <see cref="EleoncoreReturnValueApiDescriptionModel" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreReturnValueApiDescriptionModel"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EleoncoreReturnValueApiDescriptionModel eleoncoreReturnValueApiDescriptionModel, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eleoncoreReturnValueApiDescriptionModel, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EleoncoreReturnValueApiDescriptionModel" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eleoncoreReturnValueApiDescriptionModel"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EleoncoreReturnValueApiDescriptionModel eleoncoreReturnValueApiDescriptionModel, JsonSerializerOptions jsonSerializerOptions)
{
    if (eleoncoreReturnValueApiDescriptionModel.TypeOption.IsSet)
    {
        if (eleoncoreReturnValueApiDescriptionModel.TypeOption.Value != null)
        {
            writer.WritePropertyName("type");
            JsonSerializer.Serialize(writer, eleoncoreReturnValueApiDescriptionModel.Type, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("type");
        }
    }
    if (eleoncoreReturnValueApiDescriptionModel.TypeSimpleOption.IsSet)
    {
        if (eleoncoreReturnValueApiDescriptionModel.TypeSimpleOption.Value != null)
        {
            writer.WritePropertyName("typeSimple");
            JsonSerializer.Serialize(writer, eleoncoreReturnValueApiDescriptionModel.TypeSimple, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("typeSimple");
        }
    }
}

    }
}
