// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VPortal.Lifecycle.Feature.Module.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace LifecycleModule.Migrations
{
    [DbContext(typeof(LifecycleFeatureDbContext))]
    [Migration("20251118081601_Init_20251118101553")]
    partial class Init_20251118101553
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.Conditions.ConditionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<int>("ConditionResultType")
                        .HasColumnType("int");

                    b.Property<int>("ConditionTargetType")
                        .HasColumnType("int");

                    b.Property<int>("ConditionType")
                        .HasColumnType("int");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.ToTable("EcConditions", (string)null);
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.Conditions.RuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConditionEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Function")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FunctionType")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("ConditionEntityId");

                    b.ToTable("EcRuleEntity");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateActorAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovalAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovalManager")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovalNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConditional")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFormAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StateActorTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StatusUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StatusUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("EcStateActorAuditEntity", (string)null);
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateActorTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ActorType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovalAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovalManager")
                        .HasColumnType("bit");

                    b.Property<bool>("IsApprovalNeeded")
                        .HasColumnType("bit");

                    b.Property<bool>("IsConditional")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFormAdmin")
                        .HasColumnType("bit");

                    b.Property<int?>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("RefId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StateTemplateEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StateTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("StateTemplateEntityId");

                    b.ToTable("EcStateActorTemplateEntity");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<int?>("CurrentActorOrderIndex")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("StatesGroupAuditId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatesGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StatesTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("StatesGroupAuditId");

                    b.ToTable("EcStateAuditEntity", (string)null);
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReadOnly")
                        .HasColumnType("bit");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StatesGroupTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("StatesGroupTemplateId");

                    b.ToTable("EcStateTemplateEntity");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StatesGroupAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<int?>("CurrentStateOrderIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid>("StatesGroupTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.ToTable("EcStatesGroupAudits", (string)null);
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StatesGroupTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("ConcurrencyStamp");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatorId");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeleterId");

                    b.Property<DateTime?>("DeletionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletionTime");

                    b.Property<string>("DocumentObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtraProperties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ExtraProperties");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModificationTime");

                    b.Property<Guid?>("LastModifierId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifierId");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.ToTable("EcStatesGroupTemplates", (string)null);
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.Templates.StateActorTaskListSettingTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreationTime");

                    b.Property<string>("DocumentObjectType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("StateActorTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("StateActorTemplateId");

                    b.ToTable("EcStateActorTaskListSettingTemplateEntity");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.Conditions.RuleEntity", b =>
                {
                    b.HasOne("VPortal.Lifecycle.Feature.Module.Entities.Conditions.ConditionEntity", null)
                        .WithMany("Rules")
                        .HasForeignKey("ConditionEntityId");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateActorAuditEntity", b =>
                {
                    b.HasOne("VPortal.Lifecycle.Feature.Module.Entities.StateAuditEntity", "State")
                        .WithMany("Actors")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateActorTemplateEntity", b =>
                {
                    b.HasOne("VPortal.Lifecycle.Feature.Module.Entities.StateTemplateEntity", "StateTemplateEntity")
                        .WithMany("Actors")
                        .HasForeignKey("StateTemplateEntityId");

                    b.Navigation("StateTemplateEntity");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateAuditEntity", b =>
                {
                    b.HasOne("VPortal.Lifecycle.Feature.Module.Entities.StatesGroupAuditEntity", "StatesGroupAudit")
                        .WithMany("States")
                        .HasForeignKey("StatesGroupAuditId");

                    b.Navigation("StatesGroupAudit");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateTemplateEntity", b =>
                {
                    b.HasOne("VPortal.Lifecycle.Feature.Module.Entities.StatesGroupTemplateEntity", "StatesGroupTemplate")
                        .WithMany("States")
                        .HasForeignKey("StatesGroupTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StatesGroupTemplate");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.Templates.StateActorTaskListSettingTemplateEntity", b =>
                {
                    b.HasOne("VPortal.Lifecycle.Feature.Module.Entities.StateActorTemplateEntity", "StateActorTemplate")
                        .WithMany("TaskLists")
                        .HasForeignKey("StateActorTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateActorTemplate");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.Conditions.ConditionEntity", b =>
                {
                    b.Navigation("Rules");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateActorTemplateEntity", b =>
                {
                    b.Navigation("TaskLists");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateAuditEntity", b =>
                {
                    b.Navigation("Actors");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StateTemplateEntity", b =>
                {
                    b.Navigation("Actors");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StatesGroupAuditEntity", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("VPortal.Lifecycle.Feature.Module.Entities.StatesGroupTemplateEntity", b =>
                {
                    b.Navigation("States");
                });
#pragma warning restore 612, 618
        }
    }
}
