/*
 * Eleoncore API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using EleoncoreProxy.Api;
using EleoncoreProxy.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace EleoncoreProxy.Test.Api
{
    /// <summary>
    ///  Class for testing GatewayManagementApi
    /// </summary>
    public sealed class GatewayManagementApiTests : ApiTestsBase
    {
        private readonly IGatewayManagementApi _instance;

        public GatewayManagementApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IGatewayManagementApi>();
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementAcceptPendingGateway
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementAcceptPendingGatewayAsyncTest()
        {
            Client.Option<GatewayManagementAcceptPendingGatewayRequestDto> gatewayManagementAcceptPendingGatewayRequestDto = default;
            await _instance.GatewayManagementGatewayManagementAcceptPendingGatewayAsync(gatewayManagementAcceptPendingGatewayRequestDto);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementAddGateway
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementAddGatewayAsyncTest()
        {
            Client.Option<GatewayManagementGatewayDto> gatewayManagementGatewayDto = default;
            var response = await _instance.GatewayManagementGatewayManagementAddGatewayAsync(gatewayManagementGatewayDto);
            var model = response.Ok();
            Assert.IsType<string>(model);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementCancelOngoingGatewayRegistration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementCancelOngoingGatewayRegistrationAsyncTest()
        {
            Client.Option<Guid> gatewayId = default;
            var response = await _instance.GatewayManagementGatewayManagementCancelOngoingGatewayRegistrationAsync(gatewayId);
            var model = response.Ok();
            Assert.IsType<bool>(model);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementGetCurrentGatewayRegistrationKey
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementGetCurrentGatewayRegistrationKeyAsyncTest()
        {
            Client.Option<Guid> gatewayId = default;
            var response = await _instance.GatewayManagementGatewayManagementGetCurrentGatewayRegistrationKeyAsync(gatewayId);
            var model = response.Ok();
            Assert.IsType<GatewayManagementGatewayRegistrationKeyDto>(model);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementGetGateway
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementGetGatewayAsyncTest()
        {
            Client.Option<Guid> gatewayId = default;
            var response = await _instance.GatewayManagementGatewayManagementGetGatewayAsync(gatewayId);
            var model = response.Ok();
            Assert.IsType<GatewayManagementGatewayDto>(model);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementGetGatewayList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementGetGatewayListAsyncTest()
        {
            Client.Option<EleoncoreGatewayStatus> statusFilter = default;
            var response = await _instance.GatewayManagementGatewayManagementGetGatewayListAsync(statusFilter);
            var model = response.Ok();
            Assert.IsType<List<GatewayManagementGatewayDto>>(model);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementRejectPendingGateway
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementRejectPendingGatewayAsyncTest()
        {
            Client.Option<Guid> gatewayId = default;
            await _instance.GatewayManagementGatewayManagementRejectPendingGatewayAsync(gatewayId);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementRemoveGateway
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementRemoveGatewayAsyncTest()
        {
            Client.Option<Guid> gatewayId = default;
            var response = await _instance.GatewayManagementGatewayManagementRemoveGatewayAsync(gatewayId);
            var model = response.Ok();
            Assert.IsType<bool>(model);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementRequestGatewayRegistration
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementRequestGatewayRegistrationAsyncTest()
        {
            Client.Option<Guid> gatewayId = default;
            var response = await _instance.GatewayManagementGatewayManagementRequestGatewayRegistrationAsync(gatewayId);
            var model = response.Ok();
            Assert.IsType<GatewayManagementGatewayRegistrationKeyDto>(model);
        }

        /// <summary>
        /// Test GatewayManagementGatewayManagementUpdateGateway
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task GatewayManagementGatewayManagementUpdateGatewayAsyncTest()
        {
            Client.Option<GatewayManagementUpdateGatewayRequestDto> gatewayManagementUpdateGatewayRequestDto = default;
            var response = await _instance.GatewayManagementGatewayManagementUpdateGatewayAsync(gatewayManagementUpdateGatewayRequestDto);
            var model = response.Ok();
            Assert.IsType<bool>(model);
        }
    }
}
