/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using EleonsoftProxy.Api;
using EleonsoftProxy.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace EleonsoftProxy.Test.Api
{
    /// <summary>
    ///  Class for testing CommonUserApi
    /// </summary>
    public sealed class CommonUserApiTests : ApiTestsBase
    {
        private readonly ICommonUserApi _instance;

        public CommonUserApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ICommonUserApi>();
        }

        /// <summary>
        /// Test CoreCommonUserCheckPermission
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserCheckPermissionAsyncTest()
        {
            Client.Option<string> permission = default;
            var response = await _instance.CoreCommonUserCheckPermissionAsync(permission);
            var model = response.Ok();
            Assert.IsType<bool>(model);
        }

        /// <summary>
        /// Test CoreCommonUserCreate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserCreateAsyncTest()
        {
            Client.Option<EleoncoreIdentityUserCreateDto> eleoncoreIdentityUserCreateDto = default;
            var response = await _instance.CoreCommonUserCreateAsync(eleoncoreIdentityUserCreateDto);
            var model = response.Ok();
            Assert.IsType<EleoncoreIdentityUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserDeleteAsyncTest()
        {
            Client.Option<Guid> id = default;
            await _instance.CoreCommonUserDeleteAsync(id);
        }

        /// <summary>
        /// Test CoreCommonUserFindByEmail
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserFindByEmailAsyncTest()
        {
            Client.Option<string> email = default;
            var response = await _instance.CoreCommonUserFindByEmailAsync(email);
            var model = response.Ok();
            Assert.IsType<EleoncoreIdentityUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserFindByUsername
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserFindByUsernameAsyncTest()
        {
            Client.Option<string> userName = default;
            var response = await _instance.CoreCommonUserFindByUsernameAsync(userName);
            var model = response.Ok();
            Assert.IsType<EleoncoreIdentityUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetAsyncTest()
        {
            Client.Option<Guid> id = default;
            var response = await _instance.CoreCommonUserGetAsync(id);
            var model = response.Ok();
            Assert.IsType<EleoncoreIdentityUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGetAllUsersList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetAllUsersListAsyncTest()
        {
            var response = await _instance.CoreCommonUserGetAllUsersListAsync();
            var model = response.Ok();
            Assert.IsType<List<TenantManagementCommonUserDto>>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGetAssignableRoles
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetAssignableRolesAsyncTest()
        {
            var response = await _instance.CoreCommonUserGetAssignableRolesAsync();
            var model = response.Ok();
            Assert.IsType<EleoncoreListResultDtoOfEleoncoreIdentityRoleDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGetById
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetByIdAsyncTest()
        {
            Client.Option<Guid> id = default;
            var response = await _instance.CoreCommonUserGetByIdAsync(id);
            var model = response.Ok();
            Assert.IsType<TenantManagementCommonUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGetCurrentUser
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetCurrentUserAsyncTest()
        {
            var response = await _instance.CoreCommonUserGetCurrentUserAsync();
            var model = response.Ok();
            Assert.IsType<EleoncoreIdentityUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGetIdentityRoles
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetIdentityRolesAsyncTest()
        {
            Client.Option<Guid> id = default;
            var response = await _instance.CoreCommonUserGetIdentityRolesAsync(id);
            var model = response.Ok();
            Assert.IsType<EleoncoreListResultDtoOfEleoncoreIdentityRoleDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGetList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetListAsyncTest()
        {
            Client.Option<TenantManagementGetCommonUsersInput> tenantManagementGetCommonUsersInput = default;
            var response = await _instance.CoreCommonUserGetListAsync(tenantManagementGetCommonUsersInput);
            var model = response.Ok();
            Assert.IsType<EleoncorePagedResultDtoOfTenantManagementCommonUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserGetRoles
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserGetRolesAsyncTest()
        {
            Client.Option<Guid> id = default;
            var response = await _instance.CoreCommonUserGetRolesAsync(id);
            var model = response.Ok();
            Assert.IsType<List<TenantManagementCommonRoleDto>>(model);
        }

        /// <summary>
        /// Test CoreCommonUserIgnoreLastUserOtp
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserIgnoreLastUserOtpAsyncTest()
        {
            Client.Option<Guid> userId = default;
            var response = await _instance.CoreCommonUserIgnoreLastUserOtpAsync(userId);
            var model = response.Ok();
            Assert.IsType<bool>(model);
        }

        /// <summary>
        /// Test CoreCommonUserImportExcelUsers
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserImportExcelUsersAsyncTest()
        {
            Client.Option<string> file = default;
            var response = await _instance.CoreCommonUserImportExcelUsersAsync(file);
            var model = response.Ok();
            Assert.IsType<TenantManagementImportExcelUsersValueObjectDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserSetNewPassword
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserSetNewPasswordAsyncTest()
        {
            Client.Option<Guid> userId = default;
            Client.Option<string> newPassword = default;
            var response = await _instance.CoreCommonUserSetNewPasswordAsync(userId, newPassword);
            var model = response.Ok();
            Assert.IsType<bool>(model);
        }

        /// <summary>
        /// Test CoreCommonUserUpdate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserUpdateAsyncTest()
        {
            Client.Option<Guid> id = default;
            Client.Option<EleoncoreIdentityUserUpdateDto> eleoncoreIdentityUserUpdateDto = default;
            var response = await _instance.CoreCommonUserUpdateAsync(id, eleoncoreIdentityUserUpdateDto);
            var model = response.Ok();
            Assert.IsType<EleoncoreIdentityUserDto>(model);
        }

        /// <summary>
        /// Test CoreCommonUserUpdateRoles
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CoreCommonUserUpdateRolesAsyncTest()
        {
            Client.Option<Guid> id = default;
            Client.Option<EleoncoreIdentityUserUpdateRolesDto> eleoncoreIdentityUserUpdateRolesDto = default;
            await _instance.CoreCommonUserUpdateRolesAsync(id, eleoncoreIdentityUserUpdateRolesDto);
        }
    }
}
