/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using EleonsoftProxy.Api;
using EleonsoftProxy.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace EleonsoftProxy.Test.Api
{
    /// <summary>
    ///  Class for testing DocumentConversationApi
    /// </summary>
    public sealed class DocumentConversationApiTests : ApiTestsBase
    {
        private readonly IDocumentConversationApi _instance;

        public DocumentConversationApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IDocumentConversationApi>();
        }

        /// <summary>
        /// Test CollaborationDocumentConversationGetDocumentConversationInfo
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CollaborationDocumentConversationGetDocumentConversationInfoAsyncTest()
        {
            Client.Option<string> docType = default;
            Client.Option<string> documentId = default;
            var response = await _instance.CollaborationDocumentConversationGetDocumentConversationInfoAsync(docType, documentId);
            var model = response.Ok();
            Assert.IsType<CollaborationDocumentConversationInfoDto>(model);
        }

        /// <summary>
        /// Test CollaborationDocumentConversationSendDocumentChatMessages
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CollaborationDocumentConversationSendDocumentChatMessagesAsyncTest()
        {
            Client.Option<List<ModuleCollectorDocumentChatMessageDto>> moduleCollectorDocumentChatMessageDto = default;
            await _instance.CollaborationDocumentConversationSendDocumentChatMessagesAsync(moduleCollectorDocumentChatMessageDto);
        }
    }
}
