/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using EleonsoftProxy.Api;
using EleonsoftProxy.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace EleonsoftProxy.Test.Api
{
    /// <summary>
    ///  Class for testing LightweightStorageItemApi
    /// </summary>
    public sealed class LightweightStorageItemApiTests : ApiTestsBase
    {
        private readonly ILightweightStorageItemApi _instance;

        public LightweightStorageItemApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ILightweightStorageItemApi>();
        }

        /// <summary>
        /// Test StorageLightweightStorageItemGetLightweightItem
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StorageLightweightStorageItemGetLightweightItemAsyncTest()
        {
            Client.Option<string> key = default;
            var response = await _instance.StorageLightweightStorageItemGetLightweightItemAsync(key);
            var model = response.Ok();
            Assert.IsType<string>(model);
        }

        /// <summary>
        /// Test StorageLightweightStorageItemGetLightweightItems
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task StorageLightweightStorageItemGetLightweightItemsAsyncTest()
        {
            Client.Option<List<string>> keys = default;
            var response = await _instance.StorageLightweightStorageItemGetLightweightItemsAsync(keys);
            var model = response.Ok();
            Assert.IsType<List<string>>(model);
        }
    }
}
