/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using EleonsoftProxy.Api;
using EleonsoftProxy.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace EleonsoftProxy.Test.Api
{
    /// <summary>
    ///  Class for testing TemplateApi
    /// </summary>
    public sealed class TemplateApiTests : ApiTestsBase
    {
        private readonly ITemplateApi _instance;

        public TemplateApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ITemplateApi>();
        }

        /// <summary>
        /// Test EleonTemplateApplyTemplate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateApplyTemplateAsyncTest()
        {
            Client.Option<EleonApplyTemplateInput> eleonApplyTemplateInput = default;
            var response = await _instance.EleonTemplateApplyTemplateAsync(eleonApplyTemplateInput);
            var model = response.Ok();
            Assert.IsType<string>(model);
        }

        /// <summary>
        /// Test EleonTemplateCreate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateCreateAsyncTest()
        {
            Client.Option<EleonCreateUpdateTemplateDto> eleonCreateUpdateTemplateDto = default;
            var response = await _instance.EleonTemplateCreateAsync(eleonCreateUpdateTemplateDto);
            var model = response.Ok();
            Assert.IsType<EleonTemplateDto>(model);
        }

        /// <summary>
        /// Test EleonTemplateDelete
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateDeleteAsyncTest()
        {
            Client.Option<Guid> id = default;
            await _instance.EleonTemplateDeleteAsync(id);
        }

        /// <summary>
        /// Test EleonTemplateGet
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateGetAsyncTest()
        {
            Client.Option<Guid> id = default;
            var response = await _instance.EleonTemplateGetAsync(id);
            var model = response.Ok();
            Assert.IsType<EleonTemplateDto>(model);
        }

        /// <summary>
        /// Test EleonTemplateGetByNameAndType
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateGetByNameAndTypeAsyncTest()
        {
            Client.Option<string> name = default;
            Client.Option<EleonTemplateType> type = default;
            var response = await _instance.EleonTemplateGetByNameAndTypeAsync(name, type);
            var model = response.Ok();
            Assert.IsType<EleonTemplateDto>(model);
        }

        /// <summary>
        /// Test EleonTemplateGetList
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateGetListAsyncTest()
        {
            Client.Option<string> searchQuery = default;
            Client.Option<EleonTemplateType> type = default;
            Client.Option<EleoncoreTextFormat> format = default;
            Client.Option<bool> isSystem = default;
            Client.Option<string> filter = default;
            Client.Option<string> sorting = default;
            Client.Option<int> skipCount = default;
            Client.Option<int> maxResultCount = default;
            var response = await _instance.EleonTemplateGetListAsync(searchQuery, type, format, isSystem, filter, sorting, skipCount, maxResultCount);
            var model = response.Ok();
            Assert.IsType<EleoncorePagedResultDtoOfEleonMinimalTemplateDto>(model);
        }

        /// <summary>
        /// Test EleonTemplateReset
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateResetAsyncTest()
        {
            Client.Option<Guid> id = default;
            var response = await _instance.EleonTemplateResetAsync(id);
            var model = response.Ok();
            Assert.IsType<EleonTemplateDto>(model);
        }

        /// <summary>
        /// Test EleonTemplateUpdate
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task EleonTemplateUpdateAsyncTest()
        {
            Client.Option<Guid> id = default;
            Client.Option<EleonCreateUpdateTemplateDto> eleonCreateUpdateTemplateDto = default;
            var response = await _instance.EleonTemplateUpdateAsync(id, eleonCreateUpdateTemplateDto);
            var model = response.Ok();
            Assert.IsType<EleonTemplateDto>(model);
        }
    }
}
