// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Net;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text.Json;
using SharedModule.HttpApi.Helpers;
using Microsoft.AspNetCore.Http;
using EleonsoftProxy.Client;
using EleonsoftProxy.Model;
using System.Diagnostics.CodeAnalysis;

namespace EleonsoftProxy.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// This class is registered as transient.
    /// </summary>
    public interface IAbpTenantApi : IApi
    {
        void UseOAuthAuth();
        void UseApiAuth();
		void UseDefaultAuth();


        /// <summary>
        /// The class containing the events
        /// </summary>
        AbpTenantApiEvents Events { get; }

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByIdApiResponse"/>&gt;</returns>
        Task<IPagesAbpTenantFindTenantByIdApiResponse> PagesAbpTenantFindTenantByIdAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByIdApiResponse"/>&gt;</returns>
        Task<IPagesAbpTenantFindTenantByIdApiResponse> PagesAbpTenantFindTenantByIdOrDefaultAsync(Guid id, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="name"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByNameApiResponse"/>&gt;</returns>
        Task<IPagesAbpTenantFindTenantByNameApiResponse> PagesAbpTenantFindTenantByNameAsync(string name, System.Threading.CancellationToken cancellationToken = default);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <param name="name"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByNameApiResponse"/>&gt;</returns>
        Task<IPagesAbpTenantFindTenantByNameApiResponse> PagesAbpTenantFindTenantByNameOrDefaultAsync(string name, System.Threading.CancellationToken cancellationToken = default);
    }

    /// <summary>
    /// The <see cref="IPagesAbpTenantFindTenantByIdApiResponse"/>
    /// </summary>
    public interface IPagesAbpTenantFindTenantByIdApiResponse : EleonsoftProxy.Client.IApiResponse, IOk<EleonsoftProxy.Model.EleoncoreFindTenantResultDto>, IForbidden<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, IUnauthorized<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, IBadRequest<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, INotFound<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, INotImplemented<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, IInternalServerError<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 501 NotImplemented
        /// </summary>
        /// <returns></returns>
        bool IsNotImplemented { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }
    }

    /// <summary>
    /// The <see cref="IPagesAbpTenantFindTenantByNameApiResponse"/>
    /// </summary>
    public interface IPagesAbpTenantFindTenantByNameApiResponse : EleonsoftProxy.Client.IApiResponse, IOk<EleonsoftProxy.Model.EleoncoreFindTenantResultDto>, IForbidden<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, IUnauthorized<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, IBadRequest<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, INotFound<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, INotImplemented<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>, IInternalServerError<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>
    {
        /// <summary>
        /// Returns true if the response is 200 Ok
        /// </summary>
        /// <returns></returns>
        bool IsOk { get; }

        /// <summary>
        /// Returns true if the response is 403 Forbidden
        /// </summary>
        /// <returns></returns>
        bool IsForbidden { get; }

        /// <summary>
        /// Returns true if the response is 401 Unauthorized
        /// </summary>
        /// <returns></returns>
        bool IsUnauthorized { get; }

        /// <summary>
        /// Returns true if the response is 400 BadRequest
        /// </summary>
        /// <returns></returns>
        bool IsBadRequest { get; }

        /// <summary>
        /// Returns true if the response is 404 NotFound
        /// </summary>
        /// <returns></returns>
        bool IsNotFound { get; }

        /// <summary>
        /// Returns true if the response is 501 NotImplemented
        /// </summary>
        /// <returns></returns>
        bool IsNotImplemented { get; }

        /// <summary>
        /// Returns true if the response is 500 InternalServerError
        /// </summary>
        /// <returns></returns>
        bool IsInternalServerError { get; }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public class AbpTenantApiEvents
    {
        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnPagesAbpTenantFindTenantById;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorPagesAbpTenantFindTenantById;

        internal void ExecuteOnPagesAbpTenantFindTenantById(AbpTenantApi.PagesAbpTenantFindTenantByIdApiResponse apiResponse)
        {
            OnPagesAbpTenantFindTenantById?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorPagesAbpTenantFindTenantById(Exception exception)
        {
            OnErrorPagesAbpTenantFindTenantById?.Invoke(this, new ExceptionEventArgs(exception));
        }

        /// <summary>
        /// The event raised after the server response
        /// </summary>
        public event EventHandler<ApiResponseEventArgs> OnPagesAbpTenantFindTenantByName;

        /// <summary>
        /// The event raised after an error querying the server
        /// </summary>
        public event EventHandler<ExceptionEventArgs> OnErrorPagesAbpTenantFindTenantByName;

        internal void ExecuteOnPagesAbpTenantFindTenantByName(AbpTenantApi.PagesAbpTenantFindTenantByNameApiResponse apiResponse)
        {
            OnPagesAbpTenantFindTenantByName?.Invoke(this, new ApiResponseEventArgs(apiResponse));
        }

        internal void ExecuteOnErrorPagesAbpTenantFindTenantByName(Exception exception)
        {
            OnErrorPagesAbpTenantFindTenantByName?.Invoke(this, new ExceptionEventArgs(exception));
        }
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public sealed partial class AbpTenantApi : IAbpTenantApi
    {
		public HttpClient HttpClient => SdkHttpClientFactory.Create(_apiConfigurator, _accessTokenType, GetType().Name);
	
		private readonly EleoncoreSdkConfig _sdkConfig;
        private readonly JsonSerializerOptions _jsonSerializerOptions;
		private readonly ApiConfigurator _apiConfigurator;
		
		private string _accessTokenType;

        private readonly ILoggerFactory LoggerFactory;
        private readonly ILogger<AbpTenantApi> Logger;

        /// <summary>
        /// The class containing the events
        /// </summary>
        public AbpTenantApiEvents Events { get; }
		
		/// <summary>
        /// Initializes a new instance of the <see cref="AbpTenantApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AbpTenantApi() : this(ApiConfigurator.GetConfigurator("EleonsoftProxy"))
        {
        }
		
		
        /// <summary>
        /// Initializes a new instance of the <see cref="AbpTenantApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AbpTenantApi(ApiConfigurator apiConfigurator)
        {
			apiConfigurator.Validate();
		
			_apiConfigurator = apiConfigurator;
            _sdkConfig = apiConfigurator.SdkConfig;
            _jsonSerializerOptions = apiConfigurator.JsonSerializerOptions;
            LoggerFactory = apiConfigurator.LoggerFactory;
            Logger = LoggerFactory.CreateLogger<AbpTenantApi>();
            Events = new AbpTenantApiEvents();
			
        }
        


        /// <summary>
        /// Switch to use API Authorization dynamically.
        /// </summary>
        public void UseApiAuth()
		{
			if (!_sdkConfig.UseApiAuthorization)
			{
				throw new Exception("API Authorization is not configured in the SDK.");
			}

			_accessTokenType = "api";
		}

        /// <summary>
        /// Switch to use OAuth Authorization dynamically.
        /// </summary>
        public void UseOAuthAuth()
        {
            if (!_sdkConfig.UseOAuthAuthorization)
            {
                throw new Exception("OAuth Authorization is not configured in the SDK.");
            }

            _accessTokenType = "oauth";
        }
		
		public void UseDefaultAuth()
		{
			_accessTokenType = string.Empty;
		}

        public string GetBaseUrl()
		{
			if (_accessTokenType == "api" && _sdkConfig.UseApiAuthorization)
			{
				return _sdkConfig.ApiAuthUrl;
			}

			if ((_accessTokenType == "oauth" || string.IsNullOrEmpty(_accessTokenType)) && _sdkConfig.UseOAuthAuthorization)
			{
				return _sdkConfig.OAuthUrl;
			}
			
			throw new Exception("No valid authorization mode is configured or enabled.");
		}
		
		

        partial void FormatPagesAbpTenantFindTenantById(ref Guid id);

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="id"></param>
        private void AfterPagesAbpTenantFindTenantByIdDefaultImplementation(IPagesAbpTenantFindTenantByIdApiResponse apiResponseLocalVar, Guid id)
        {
            bool suppressDefaultLog = false;
            AfterPagesAbpTenantFindTenantById(ref suppressDefaultLog, apiResponseLocalVar, id);
            if (!suppressDefaultLog)
                Logger.LogDebug("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="id"></param>
        partial void AfterPagesAbpTenantFindTenantById(ref bool suppressDefaultLog, IPagesAbpTenantFindTenantByIdApiResponse apiResponseLocalVar, Guid id);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exception"></param>
        /// <param name="pathFormat"></param>
        /// <param name="path"></param>
        /// <param name="id"></param>
        private void OnErrorPagesAbpTenantFindTenantByIdDefaultImplementation(Exception exception, string pathFormat, string path, Guid id)
        {
            bool suppressDefaultLog = false;
            OnErrorPagesAbpTenantFindTenantById(ref suppressDefaultLog, exception, pathFormat, path, id);
            if (!suppressDefaultLog)
                Logger.LogError(exception, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="exception"></param>
        /// <param name="pathFormat"></param>
        /// <param name="path"></param>
        /// <param name="id"></param>
        partial void OnErrorPagesAbpTenantFindTenantById(ref bool suppressDefaultLog, Exception exception, string pathFormat, string path, Guid id);

        /// <summary>
        ///  
        /// </summary>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByIdApiResponse"/>&gt;</returns>
        public async Task<IPagesAbpTenantFindTenantByIdApiResponse> PagesAbpTenantFindTenantByIdOrDefaultAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await PagesAbpTenantFindTenantByIdAsync(id, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByIdApiResponse"/>&gt;</returns>
        public async Task<IPagesAbpTenantFindTenantByIdApiResponse> PagesAbpTenantFindTenantByIdAsync(Guid id, System.Threading.CancellationToken cancellationToken = default)
        {
			var httpClient = SdkHttpClientFactory.Create(_apiConfigurator, _accessTokenType, "AbpTenantApi");
			
			UriBuilder uriBuilderLocalVar = new UriBuilder(httpClient.BaseAddress);
			
            try
            {
                FormatPagesAbpTenantFindTenantById(ref id);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    // Construct URI
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.TrimEnd('/') + "/api/abp/multi-tenancy/tenants/by-id/{id}";

                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bid%7D", Uri.EscapeDataString(id.ToString()));


					
					httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;


                    string[] acceptLocalVars = new string[] {
                        "text/plain",
                        "application/json",
                        "text/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await httpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<PagesAbpTenantFindTenantByIdApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<PagesAbpTenantFindTenantByIdApiResponse>();

                        PagesAbpTenantFindTenantByIdApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/abp/multi-tenancy/tenants/by-id/{id}", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterPagesAbpTenantFindTenantByIdDefaultImplementation(apiResponseLocalVar, id);

                        Events.ExecuteOnPagesAbpTenantFindTenantById(apiResponseLocalVar);
						
                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorPagesAbpTenantFindTenantByIdDefaultImplementation(e, "/api/abp/multi-tenancy/tenants/by-id/{id}", uriBuilderLocalVar.Path, id);
                Events.ExecuteOnErrorPagesAbpTenantFindTenantById(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="PagesAbpTenantFindTenantByIdApiResponse"/>
        /// </summary>
        public partial class PagesAbpTenantFindTenantByIdApiResponse : EleonsoftProxy.Client.ApiResponse, IPagesAbpTenantFindTenantByIdApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PagesAbpTenantFindTenantByIdApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="PagesAbpTenantFindTenantByIdApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PagesAbpTenantFindTenantByIdApiResponse(ILogger<PagesAbpTenantFindTenantByIdApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreFindTenantResultDto Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreFindTenantResultDto>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreFindTenantResultDto result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse Forbidden()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse Unauthorized()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 501 NotImplemented
            /// </summary>
            /// <returns></returns>
            public bool IsNotImplemented => 501 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 501 NotImplemented
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse NotImplemented()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotImplemented
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 501 NotImplemented and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotImplemented([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = NotImplemented();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)501);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }

        partial void FormatPagesAbpTenantFindTenantByName(ref string name);

        /// <summary>
        /// Validates the request parameters
        /// </summary>
        /// <param name="name"></param>
        /// <returns></returns>
        private void ValidatePagesAbpTenantFindTenantByName(string name)
        {
            if (name == null)
                throw new ArgumentNullException(nameof(name));
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="name"></param>
        private void AfterPagesAbpTenantFindTenantByNameDefaultImplementation(IPagesAbpTenantFindTenantByNameApiResponse apiResponseLocalVar, string name)
        {
            bool suppressDefaultLog = false;
            AfterPagesAbpTenantFindTenantByName(ref suppressDefaultLog, apiResponseLocalVar, name);
            if (!suppressDefaultLog)
                Logger.LogDebug("{0,-9} | {1} | {3}", (apiResponseLocalVar.DownloadedAt - apiResponseLocalVar.RequestedAt).TotalSeconds, apiResponseLocalVar.StatusCode, apiResponseLocalVar.Path);
        }

        /// <summary>
        /// Processes the server response
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="apiResponseLocalVar"></param>
        /// <param name="name"></param>
        partial void AfterPagesAbpTenantFindTenantByName(ref bool suppressDefaultLog, IPagesAbpTenantFindTenantByNameApiResponse apiResponseLocalVar, string name);

        /// <summary>
        /// Logs exceptions that occur while retrieving the server response
        /// </summary>
        /// <param name="exception"></param>
        /// <param name="pathFormat"></param>
        /// <param name="path"></param>
        /// <param name="name"></param>
        private void OnErrorPagesAbpTenantFindTenantByNameDefaultImplementation(Exception exception, string pathFormat, string path, string name)
        {
            bool suppressDefaultLog = false;
            OnErrorPagesAbpTenantFindTenantByName(ref suppressDefaultLog, exception, pathFormat, path, name);
            if (!suppressDefaultLog)
                Logger.LogError(exception, "An error occurred while sending the request to the server.");
        }

        /// <summary>
        /// A partial method that gives developers a way to provide customized exception handling
        /// </summary>
        /// <param name="suppressDefaultLog"></param>
        /// <param name="exception"></param>
        /// <param name="pathFormat"></param>
        /// <param name="path"></param>
        /// <param name="name"></param>
        partial void OnErrorPagesAbpTenantFindTenantByName(ref bool suppressDefaultLog, Exception exception, string pathFormat, string path, string name);

        /// <summary>
        ///  
        /// </summary>
        /// <param name="name"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByNameApiResponse"/>&gt;</returns>
        public async Task<IPagesAbpTenantFindTenantByNameApiResponse> PagesAbpTenantFindTenantByNameOrDefaultAsync(string name, System.Threading.CancellationToken cancellationToken = default)
        {
            try
            {
                return await PagesAbpTenantFindTenantByNameAsync(name, cancellationToken).ConfigureAwait(false);
            }
            catch (Exception)
            {
                return null;
            }
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="name"></param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns><see cref="Task"/>&lt;<see cref="IPagesAbpTenantFindTenantByNameApiResponse"/>&gt;</returns>
        public async Task<IPagesAbpTenantFindTenantByNameApiResponse> PagesAbpTenantFindTenantByNameAsync(string name, System.Threading.CancellationToken cancellationToken = default)
        {
			var httpClient = SdkHttpClientFactory.Create(_apiConfigurator, _accessTokenType, "AbpTenantApi");
			
			UriBuilder uriBuilderLocalVar = new UriBuilder(httpClient.BaseAddress);
			
            try
            {
                ValidatePagesAbpTenantFindTenantByName(name);

                FormatPagesAbpTenantFindTenantByName(ref name);

                using (HttpRequestMessage httpRequestMessageLocalVar = new HttpRequestMessage())
                {
                    // Construct URI
                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.TrimEnd('/') + "/api/abp/multi-tenancy/tenants/by-name/{name}";

                    uriBuilderLocalVar.Path = uriBuilderLocalVar.Path.Replace("%7Bname%7D", Uri.EscapeDataString(name.ToString()));


					
					httpRequestMessageLocalVar.RequestUri = uriBuilderLocalVar.Uri;


                    string[] acceptLocalVars = new string[] {
                        "text/plain",
                        "application/json",
                        "text/json"
                    };

                    string acceptLocalVar = ClientUtils.SelectHeaderAccept(acceptLocalVars);

                    if (acceptLocalVar != null)
                        httpRequestMessageLocalVar.Headers.Accept.Add(new MediaTypeWithQualityHeaderValue(acceptLocalVar));

                    httpRequestMessageLocalVar.Method = HttpMethod.Get;

                    DateTime requestedAtLocalVar = DateTime.UtcNow;

                    using (HttpResponseMessage httpResponseMessageLocalVar = await httpClient.SendAsync(httpRequestMessageLocalVar, cancellationToken).ConfigureAwait(false))
                    {
                        string responseContentLocalVar = await httpResponseMessageLocalVar.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);

                        ILogger<PagesAbpTenantFindTenantByNameApiResponse> apiResponseLoggerLocalVar = LoggerFactory.CreateLogger<PagesAbpTenantFindTenantByNameApiResponse>();

                        PagesAbpTenantFindTenantByNameApiResponse apiResponseLocalVar = new(apiResponseLoggerLocalVar, httpRequestMessageLocalVar, httpResponseMessageLocalVar, responseContentLocalVar, "/api/abp/multi-tenancy/tenants/by-name/{name}", requestedAtLocalVar, _jsonSerializerOptions);

                        AfterPagesAbpTenantFindTenantByNameDefaultImplementation(apiResponseLocalVar, name);

                        Events.ExecuteOnPagesAbpTenantFindTenantByName(apiResponseLocalVar);
						
                        return apiResponseLocalVar;
                    }
                }
            }
            catch(Exception e)
            {
                OnErrorPagesAbpTenantFindTenantByNameDefaultImplementation(e, "/api/abp/multi-tenancy/tenants/by-name/{name}", uriBuilderLocalVar.Path, name);
                Events.ExecuteOnErrorPagesAbpTenantFindTenantByName(e);
                throw;
            }
        }

        /// <summary>
        /// The <see cref="PagesAbpTenantFindTenantByNameApiResponse"/>
        /// </summary>
        public partial class PagesAbpTenantFindTenantByNameApiResponse : EleonsoftProxy.Client.ApiResponse, IPagesAbpTenantFindTenantByNameApiResponse
        {
            /// <summary>
            /// The logger
            /// </summary>
            public ILogger<PagesAbpTenantFindTenantByNameApiResponse> Logger { get; }

            /// <summary>
            /// The <see cref="PagesAbpTenantFindTenantByNameApiResponse"/>
            /// </summary>
            /// <param name="logger"></param>
            /// <param name="httpRequestMessage"></param>
            /// <param name="httpResponseMessage"></param>
            /// <param name="rawContent"></param>
            /// <param name="path"></param>
            /// <param name="requestedAt"></param>
            /// <param name="jsonSerializerOptions"></param>
            public PagesAbpTenantFindTenantByNameApiResponse(ILogger<PagesAbpTenantFindTenantByNameApiResponse> logger, System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage, string rawContent, string path, DateTime requestedAt, System.Text.Json.JsonSerializerOptions jsonSerializerOptions) : base(httpRequestMessage, httpResponseMessage, rawContent, path, requestedAt, jsonSerializerOptions)
            {
                Logger = logger;
                OnCreated(httpRequestMessage, httpResponseMessage);
            }

            partial void OnCreated(global::System.Net.Http.HttpRequestMessage httpRequestMessage, System.Net.Http.HttpResponseMessage httpResponseMessage);

            /// <summary>
            /// Returns true if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public bool IsOk => 200 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 200 Ok
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreFindTenantResultDto Ok()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsOk
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreFindTenantResultDto>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 200 Ok and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryOk([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreFindTenantResultDto result)
            {
                result = null;

                try
                {
                    result = Ok();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)200);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public bool IsForbidden => 403 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 403 Forbidden
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse Forbidden()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsForbidden
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 403 Forbidden and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryForbidden([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = Forbidden();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)403);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public bool IsUnauthorized => 401 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 401 Unauthorized
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse Unauthorized()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsUnauthorized
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 401 Unauthorized and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryUnauthorized([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = Unauthorized();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)401);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public bool IsBadRequest => 400 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 400 BadRequest
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse BadRequest()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsBadRequest
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 400 BadRequest and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryBadRequest([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = BadRequest();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)400);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public bool IsNotFound => 404 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 404 NotFound
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse NotFound()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotFound
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 404 NotFound and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotFound([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = NotFound();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)404);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 501 NotImplemented
            /// </summary>
            /// <returns></returns>
            public bool IsNotImplemented => 501 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 501 NotImplemented
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse NotImplemented()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsNotImplemented
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 501 NotImplemented and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryNotImplemented([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = NotImplemented();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)501);
                }

                return result != null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public bool IsInternalServerError => 500 == (int)StatusCode;

            /// <summary>
            /// Deserializes the response if the response is 500 InternalServerError
            /// </summary>
            /// <returns></returns>
            public EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse InternalServerError()
            {
                // This logic may be modified with the AsModel.mustache template
                return IsInternalServerError
                    ? System.Text.Json.JsonSerializer.Deserialize<EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse>(RawContent, _jsonSerializerOptions)
                    : null;
            }

            /// <summary>
            /// Returns true if the response is 500 InternalServerError and the deserialized response is not null
            /// </summary>
            /// <param name="result"></param>
            /// <returns></returns>
            public bool TryInternalServerError([NotNullWhen(true)]out EleonsoftProxy.Model.EleoncoreRemoteServiceErrorResponse result)
            {
                result = null;

                try
                {
                    result = InternalServerError();
                } catch (Exception e)
                {
                    OnDeserializationErrorDefaultImplementation(e, (HttpStatusCode)500);
                }

                return result != null;
            }

            private void OnDeserializationErrorDefaultImplementation(Exception exception, HttpStatusCode httpStatusCode)
            {
                bool suppressDefaultLog = false;
                OnDeserializationError(ref suppressDefaultLog, exception, httpStatusCode);
                if (!suppressDefaultLog)
                    Logger.LogError(exception, "An error occurred while deserializing the {code} response.", httpStatusCode);
            }

            partial void OnDeserializationError(ref bool suppressDefaultLog, Exception exception, HttpStatusCode httpStatusCode);
        }
    }
}

