// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// AccountingReceiptDto
    /// </summary>
    public partial class AccountingReceiptDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountingReceiptDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="tenantId">tenantId</param>
        /// <param name="invoiceEntityId">invoiceEntityId</param>
        /// <param name="paymentDate">paymentDate</param>
        /// <param name="amount">amount</param>
        /// <param name="paymentType">paymentType</param>
        /// <param name="transaction">transaction</param>
        [JsonConstructor]
        public AccountingReceiptDto(Option<Guid?> id = default, Option<Guid?> tenantId = default, Option<Guid?> invoiceEntityId = default, Option<DateTime?> paymentDate = default, Option<double?> amount = default, Option<EleoncorePaymentType?> paymentType = default, Option<string> transaction = default)
        {
            IdOption = id;
            TenantIdOption = tenantId;
            InvoiceEntityIdOption = invoiceEntityId;
            PaymentDateOption = paymentDate;
            AmountOption = amount;
            PaymentTypeOption = paymentType;
            TransactionOption = transaction;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of PaymentType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleoncorePaymentType?> PaymentTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaymentType
        /// </summary>
        [JsonPropertyName("paymentType")]
        public EleoncorePaymentType? PaymentType { get { return this.PaymentTypeOption; } set { this.PaymentTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TenantId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> TenantIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TenantId
        /// </summary>
        [JsonPropertyName("tenantId")]
        public Guid? TenantId { get { return this.TenantIdOption; } set { this.TenantIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of InvoiceEntityId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> InvoiceEntityIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets InvoiceEntityId
        /// </summary>
        [JsonPropertyName("invoiceEntityId")]
        public Guid? InvoiceEntityId { get { return this.InvoiceEntityIdOption; } set { this.InvoiceEntityIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of PaymentDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> PaymentDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets PaymentDate
        /// </summary>
        [JsonPropertyName("paymentDate")]
        public DateTime? PaymentDate { get { return this.PaymentDateOption; } set { this.PaymentDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Amount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<double?> AmountOption { get; private set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [JsonPropertyName("amount")]
        public double? Amount { get { return this.AmountOption; } set { this.AmountOption = new(value); } }

        /// <summary>
        /// Used to track the state of Transaction
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TransactionOption { get; private set; }

        /// <summary>
        /// Gets or Sets Transaction
        /// </summary>
        [JsonPropertyName("transaction")]
        public string Transaction { get { return this.TransactionOption; } set { this.TransactionOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AccountingReceiptDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  TenantId: ").Append(TenantId).Append("\n");
            sb.Append("  InvoiceEntityId: ").Append(InvoiceEntityId).Append("\n");
            sb.Append("  PaymentDate: ").Append(PaymentDate).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  PaymentType: ").Append(PaymentType).Append("\n");
            sb.Append("  Transaction: ").Append(Transaction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="AccountingReceiptDto" />
    /// </summary>
    public class AccountingReceiptDtoJsonConverter : JsonConverter<AccountingReceiptDto>
    {
        /// <summary>
        /// The format to use to serialize PaymentDate
        /// </summary>
        public static string PaymentDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="AccountingReceiptDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override AccountingReceiptDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<Guid?> tenantId = default;
            Option<Guid?> invoiceEntityId = default;
            Option<DateTime?> paymentDate = default;
            Option<double?> amount = default;
            Option<EleoncorePaymentType?> paymentType = default;
            Option<string> transaction = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "tenantId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                tenantId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "invoiceEntityId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                invoiceEntityId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "paymentDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                paymentDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "amount":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                amount = new Option<double?>(utf8JsonReader.GetDouble());
                            break;
                        case "paymentType":
                            string paymentTypeRawValue = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                            if (paymentTypeRawValue != null)
                                paymentType = new Option<EleoncorePaymentType?>(EleoncorePaymentTypeValueConverter.FromStringOrDefault(paymentTypeRawValue));
                            break;
                        case "transaction":
                            transaction = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class AccountingReceiptDto.");

            if (invoiceEntityId.IsSet && invoiceEntityId.Value == null)
                throw new ArgumentNullException(nameof(invoiceEntityId), "Property is not nullable for class AccountingReceiptDto.");

            if (paymentDate.IsSet && paymentDate.Value == null)
                throw new ArgumentNullException(nameof(paymentDate), "Property is not nullable for class AccountingReceiptDto.");

            if (amount.IsSet && amount.Value == null)
                throw new ArgumentNullException(nameof(amount), "Property is not nullable for class AccountingReceiptDto.");

            if (paymentType.IsSet && paymentType.Value == null)
                throw new ArgumentNullException(nameof(paymentType), "Property is not nullable for class AccountingReceiptDto.");


            return new AccountingReceiptDto(id, tenantId, invoiceEntityId, paymentDate, amount, paymentType, transaction);
        }

        /// <summary>
        /// Serializes a <see cref="AccountingReceiptDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="accountingReceiptDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, AccountingReceiptDto accountingReceiptDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, accountingReceiptDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="AccountingReceiptDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="accountingReceiptDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, AccountingReceiptDto accountingReceiptDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (accountingReceiptDto.IdOption.IsSet)
    {
        writer.WritePropertyName("id");
        JsonSerializer.Serialize(writer, accountingReceiptDto.Id, jsonSerializerOptions);
    }
    if (accountingReceiptDto.TenantIdOption.IsSet)
    {
        if (accountingReceiptDto.TenantIdOption.Value != null)
        {
            writer.WritePropertyName("tenantId");
            JsonSerializer.Serialize(writer, accountingReceiptDto.TenantId, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("tenantId");
        }
    }
    if (accountingReceiptDto.InvoiceEntityIdOption.IsSet)
    {
        writer.WritePropertyName("invoiceEntityId");
        JsonSerializer.Serialize(writer, accountingReceiptDto.InvoiceEntityId, jsonSerializerOptions);
    }
    if (accountingReceiptDto.PaymentDateOption.IsSet)
    {
        writer.WritePropertyName("paymentDate");
        JsonSerializer.Serialize(writer, accountingReceiptDto.PaymentDate, jsonSerializerOptions);
    }
    if (accountingReceiptDto.AmountOption.IsSet)
    {
        writer.WritePropertyName("amount");
        JsonSerializer.Serialize(writer, accountingReceiptDto.Amount, jsonSerializerOptions);
    }
    if (accountingReceiptDto.PaymentTypeOption.IsSet)
    {
        writer.WritePropertyName("paymentType");
        JsonSerializer.Serialize(writer, accountingReceiptDto.PaymentType, jsonSerializerOptions);
    }
    if (accountingReceiptDto.TransactionOption.IsSet)
    {
        if (accountingReceiptDto.TransactionOption.Value != null)
        {
            writer.WritePropertyName("transaction");
            JsonSerializer.Serialize(writer, accountingReceiptDto.Transaction, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("transaction");
        }
    }
}

    }
}
