// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// EleoncoreGetFeatureListResultDto
    /// </summary>
    public partial class EleoncoreGetFeatureListResultDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EleoncoreGetFeatureListResultDto" /> class.
        /// </summary>
        /// <param name="groups">groups</param>
        [JsonConstructor]
        public EleoncoreGetFeatureListResultDto(Option<List<EleoncoreFeatureGroupDto>> groups = default)
        {
            GroupsOption = groups;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Groups
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<EleoncoreFeatureGroupDto>> GroupsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Groups
        /// </summary>
        [JsonPropertyName("groups")]
        public List<EleoncoreFeatureGroupDto> Groups { get { return this.GroupsOption; } set { this.GroupsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EleoncoreGetFeatureListResultDto {\n");
            sb.Append("  Groups: ").Append(Groups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreGetFeatureListResultDto" />
    /// </summary>
    public class EleoncoreGetFeatureListResultDtoJsonConverter : JsonConverter<EleoncoreGetFeatureListResultDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="EleoncoreGetFeatureListResultDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EleoncoreGetFeatureListResultDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<EleoncoreFeatureGroupDto>> groups = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "groups":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                groups = new Option<List<EleoncoreFeatureGroupDto>>(JsonSerializer.Deserialize<List<EleoncoreFeatureGroupDto>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }


            return new EleoncoreGetFeatureListResultDto(groups);
        }

        /// <summary>
        /// Serializes a <see cref="EleoncoreGetFeatureListResultDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreGetFeatureListResultDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EleoncoreGetFeatureListResultDto eleoncoreGetFeatureListResultDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eleoncoreGetFeatureListResultDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EleoncoreGetFeatureListResultDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eleoncoreGetFeatureListResultDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EleoncoreGetFeatureListResultDto eleoncoreGetFeatureListResultDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (eleoncoreGetFeatureListResultDto.GroupsOption.IsSet)
    {
        if (eleoncoreGetFeatureListResultDto.GroupsOption.Value != null)
        {
            writer.WritePropertyName("groups");
            JsonSerializer.Serialize(writer, eleoncoreGetFeatureListResultDto.Groups, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("groups");
        }
    }
}

    }
}
