// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// EleoncoreExtensionPropertyUiLookupDto
    /// </summary>
    public partial class EleoncoreExtensionPropertyUiLookupDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EleoncoreExtensionPropertyUiLookupDto" /> class.
        /// </summary>
        /// <param name="url">url</param>
        /// <param name="resultListPropertyName">resultListPropertyName</param>
        /// <param name="displayPropertyName">displayPropertyName</param>
        /// <param name="valuePropertyName">valuePropertyName</param>
        /// <param name="filterParamName">filterParamName</param>
        [JsonConstructor]
        public EleoncoreExtensionPropertyUiLookupDto(Option<string> url = default, Option<string> resultListPropertyName = default, Option<string> displayPropertyName = default, Option<string> valuePropertyName = default, Option<string> filterParamName = default)
        {
            UrlOption = url;
            ResultListPropertyNameOption = resultListPropertyName;
            DisplayPropertyNameOption = displayPropertyName;
            ValuePropertyNameOption = valuePropertyName;
            FilterParamNameOption = filterParamName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get { return this.UrlOption; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ResultListPropertyName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ResultListPropertyNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ResultListPropertyName
        /// </summary>
        [JsonPropertyName("resultListPropertyName")]
        public string ResultListPropertyName { get { return this.ResultListPropertyNameOption; } set { this.ResultListPropertyNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of DisplayPropertyName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DisplayPropertyNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets DisplayPropertyName
        /// </summary>
        [JsonPropertyName("displayPropertyName")]
        public string DisplayPropertyName { get { return this.DisplayPropertyNameOption; } set { this.DisplayPropertyNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ValuePropertyName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ValuePropertyNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ValuePropertyName
        /// </summary>
        [JsonPropertyName("valuePropertyName")]
        public string ValuePropertyName { get { return this.ValuePropertyNameOption; } set { this.ValuePropertyNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of FilterParamName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> FilterParamNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets FilterParamName
        /// </summary>
        [JsonPropertyName("filterParamName")]
        public string FilterParamName { get { return this.FilterParamNameOption; } set { this.FilterParamNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EleoncoreExtensionPropertyUiLookupDto {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  ResultListPropertyName: ").Append(ResultListPropertyName).Append("\n");
            sb.Append("  DisplayPropertyName: ").Append(DisplayPropertyName).Append("\n");
            sb.Append("  ValuePropertyName: ").Append(ValuePropertyName).Append("\n");
            sb.Append("  FilterParamName: ").Append(FilterParamName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreExtensionPropertyUiLookupDto" />
    /// </summary>
    public class EleoncoreExtensionPropertyUiLookupDtoJsonConverter : JsonConverter<EleoncoreExtensionPropertyUiLookupDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="EleoncoreExtensionPropertyUiLookupDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EleoncoreExtensionPropertyUiLookupDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> url = default;
            Option<string> resultListPropertyName = default;
            Option<string> displayPropertyName = default;
            Option<string> valuePropertyName = default;
            Option<string> filterParamName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "url":
                            url = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "resultListPropertyName":
                            resultListPropertyName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "displayPropertyName":
                            displayPropertyName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "valuePropertyName":
                            valuePropertyName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "filterParamName":
                            filterParamName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }


            return new EleoncoreExtensionPropertyUiLookupDto(url, resultListPropertyName, displayPropertyName, valuePropertyName, filterParamName);
        }

        /// <summary>
        /// Serializes a <see cref="EleoncoreExtensionPropertyUiLookupDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreExtensionPropertyUiLookupDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EleoncoreExtensionPropertyUiLookupDto eleoncoreExtensionPropertyUiLookupDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eleoncoreExtensionPropertyUiLookupDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EleoncoreExtensionPropertyUiLookupDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eleoncoreExtensionPropertyUiLookupDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EleoncoreExtensionPropertyUiLookupDto eleoncoreExtensionPropertyUiLookupDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (eleoncoreExtensionPropertyUiLookupDto.UrlOption.IsSet)
    {
        if (eleoncoreExtensionPropertyUiLookupDto.UrlOption.Value != null)
        {
            writer.WritePropertyName("url");
            JsonSerializer.Serialize(writer, eleoncoreExtensionPropertyUiLookupDto.Url, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("url");
        }
    }
    if (eleoncoreExtensionPropertyUiLookupDto.ResultListPropertyNameOption.IsSet)
    {
        if (eleoncoreExtensionPropertyUiLookupDto.ResultListPropertyNameOption.Value != null)
        {
            writer.WritePropertyName("resultListPropertyName");
            JsonSerializer.Serialize(writer, eleoncoreExtensionPropertyUiLookupDto.ResultListPropertyName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("resultListPropertyName");
        }
    }
    if (eleoncoreExtensionPropertyUiLookupDto.DisplayPropertyNameOption.IsSet)
    {
        if (eleoncoreExtensionPropertyUiLookupDto.DisplayPropertyNameOption.Value != null)
        {
            writer.WritePropertyName("displayPropertyName");
            JsonSerializer.Serialize(writer, eleoncoreExtensionPropertyUiLookupDto.DisplayPropertyName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("displayPropertyName");
        }
    }
    if (eleoncoreExtensionPropertyUiLookupDto.ValuePropertyNameOption.IsSet)
    {
        if (eleoncoreExtensionPropertyUiLookupDto.ValuePropertyNameOption.Value != null)
        {
            writer.WritePropertyName("valuePropertyName");
            JsonSerializer.Serialize(writer, eleoncoreExtensionPropertyUiLookupDto.ValuePropertyName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("valuePropertyName");
        }
    }
    if (eleoncoreExtensionPropertyUiLookupDto.FilterParamNameOption.IsSet)
    {
        if (eleoncoreExtensionPropertyUiLookupDto.FilterParamNameOption.Value != null)
        {
            writer.WritePropertyName("filterParamName");
            JsonSerializer.Serialize(writer, eleoncoreExtensionPropertyUiLookupDto.FilterParamName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("filterParamName");
        }
    }
}

    }
}
