// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// Defines Eleoncore.LifecycleActorTypes
    /// </summary>
    public enum EleoncoreLifecycleActorTypes
    {
        /// <summary>
        /// Enum Initiator for value: 0
        /// </summary>
        Initiator = 0,

        /// <summary>
        /// Enum User for value: 1
        /// </summary>
        User = 1,

        /// <summary>
        /// Enum Role for value: 2
        /// </summary>
        Role = 2,

        /// <summary>
        /// Enum Beneficiary for value: 3
        /// </summary>
        Beneficiary = 3
    }

    /// <summary>
    /// Converts <see cref="EleoncoreLifecycleActorTypes"/> to and from the JSON value
    /// </summary>
    public static class EleoncoreLifecycleActorTypesValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="EleoncoreLifecycleActorTypes"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleoncoreLifecycleActorTypes FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return EleoncoreLifecycleActorTypes.Initiator;

            if (value.Equals((1).ToString()))
                return EleoncoreLifecycleActorTypes.User;

            if (value.Equals((2).ToString()))
                return EleoncoreLifecycleActorTypes.Role;

            if (value.Equals((3).ToString()))
                return EleoncoreLifecycleActorTypes.Beneficiary;

            throw new NotImplementedException($"Could not convert value to type EleoncoreLifecycleActorTypes: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="EleoncoreLifecycleActorTypes"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleoncoreLifecycleActorTypes? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return EleoncoreLifecycleActorTypes.Initiator;

            if (value.Equals((1).ToString()))
                return EleoncoreLifecycleActorTypes.User;

            if (value.Equals((2).ToString()))
                return EleoncoreLifecycleActorTypes.Role;

            if (value.Equals((3).ToString()))
                return EleoncoreLifecycleActorTypes.Beneficiary;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EleoncoreLifecycleActorTypes"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(EleoncoreLifecycleActorTypes value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreLifecycleActorTypes"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class EleoncoreLifecycleActorTypesJsonConverter : JsonConverter<EleoncoreLifecycleActorTypes>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleoncoreLifecycleActorTypes Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleoncoreLifecycleActorTypes? result = rawValue == null
                ? null
                : EleoncoreLifecycleActorTypesValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EleoncoreLifecycleActorTypes to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreLifecycleActorTypes"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleoncoreLifecycleActorTypes eleoncoreLifecycleActorTypes, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleoncoreLifecycleActorTypes.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreLifecycleActorTypes"/>
    /// </summary>
    public class EleoncoreLifecycleActorTypesNullableJsonConverter : JsonConverter<EleoncoreLifecycleActorTypes?>
    {
        /// <summary>
        /// Returns a EleoncoreLifecycleActorTypes from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleoncoreLifecycleActorTypes? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleoncoreLifecycleActorTypes? result = rawValue == null
                ? null
                : EleoncoreLifecycleActorTypesValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreLifecycleActorTypes"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleoncoreLifecycleActorTypes? eleoncoreLifecycleActorTypes, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleoncoreLifecycleActorTypes?.ToString() ?? "null");
        }
    }
}
