// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// EleoncoreApplicationSettingConfigurationDto
    /// </summary>
    public partial class EleoncoreApplicationSettingConfigurationDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EleoncoreApplicationSettingConfigurationDto" /> class.
        /// </summary>
        /// <param name="values">values</param>
        [JsonConstructor]
        public EleoncoreApplicationSettingConfigurationDto(Option<Dictionary<string, string>> values = default)
        {
            ValuesOption = values;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Values
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, string>> ValuesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Values
        /// </summary>
        [JsonPropertyName("values")]
        public Dictionary<string, string> Values { get { return this.ValuesOption; } set { this.ValuesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EleoncoreApplicationSettingConfigurationDto {\n");
            sb.Append("  Values: ").Append(Values).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreApplicationSettingConfigurationDto" />
    /// </summary>
    public class EleoncoreApplicationSettingConfigurationDtoJsonConverter : JsonConverter<EleoncoreApplicationSettingConfigurationDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="EleoncoreApplicationSettingConfigurationDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EleoncoreApplicationSettingConfigurationDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Dictionary<string, string>> values = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "values":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                values = new Option<Dictionary<string, string>>(JsonSerializer.Deserialize<Dictionary<string, string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }


            return new EleoncoreApplicationSettingConfigurationDto(values);
        }

        /// <summary>
        /// Serializes a <see cref="EleoncoreApplicationSettingConfigurationDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreApplicationSettingConfigurationDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EleoncoreApplicationSettingConfigurationDto eleoncoreApplicationSettingConfigurationDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eleoncoreApplicationSettingConfigurationDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EleoncoreApplicationSettingConfigurationDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eleoncoreApplicationSettingConfigurationDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EleoncoreApplicationSettingConfigurationDto eleoncoreApplicationSettingConfigurationDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (eleoncoreApplicationSettingConfigurationDto.ValuesOption.IsSet)
    {
        if (eleoncoreApplicationSettingConfigurationDto.ValuesOption.Value != null)
        {
            writer.WritePropertyName("values");
            JsonSerializer.Serialize(writer, eleoncoreApplicationSettingConfigurationDto.Values, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("values");
        }
    }
}

    }
}
