// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// Defines Eleoncore.LifecycleApprovalType
    /// </summary>
    public enum EleoncoreLifecycleApprovalType
    {
        /// <summary>
        /// Enum Regular for value: 0
        /// </summary>
        Regular = 0,

        /// <summary>
        /// Enum Parallel for value: 1
        /// </summary>
        Parallel = 1,

        /// <summary>
        /// Enum AtLeast for value: 2
        /// </summary>
        AtLeast = 2
    }

    /// <summary>
    /// Converts <see cref="EleoncoreLifecycleApprovalType"/> to and from the JSON value
    /// </summary>
    public static class EleoncoreLifecycleApprovalTypeValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="EleoncoreLifecycleApprovalType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleoncoreLifecycleApprovalType FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return EleoncoreLifecycleApprovalType.Regular;

            if (value.Equals((1).ToString()))
                return EleoncoreLifecycleApprovalType.Parallel;

            if (value.Equals((2).ToString()))
                return EleoncoreLifecycleApprovalType.AtLeast;

            throw new NotImplementedException($"Could not convert value to type EleoncoreLifecycleApprovalType: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="EleoncoreLifecycleApprovalType"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleoncoreLifecycleApprovalType? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return EleoncoreLifecycleApprovalType.Regular;

            if (value.Equals((1).ToString()))
                return EleoncoreLifecycleApprovalType.Parallel;

            if (value.Equals((2).ToString()))
                return EleoncoreLifecycleApprovalType.AtLeast;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EleoncoreLifecycleApprovalType"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(EleoncoreLifecycleApprovalType value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreLifecycleApprovalType"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class EleoncoreLifecycleApprovalTypeJsonConverter : JsonConverter<EleoncoreLifecycleApprovalType>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleoncoreLifecycleApprovalType Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleoncoreLifecycleApprovalType? result = rawValue == null
                ? null
                : EleoncoreLifecycleApprovalTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EleoncoreLifecycleApprovalType to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreLifecycleApprovalType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleoncoreLifecycleApprovalType eleoncoreLifecycleApprovalType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleoncoreLifecycleApprovalType.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreLifecycleApprovalType"/>
    /// </summary>
    public class EleoncoreLifecycleApprovalTypeNullableJsonConverter : JsonConverter<EleoncoreLifecycleApprovalType?>
    {
        /// <summary>
        /// Returns a EleoncoreLifecycleApprovalType from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleoncoreLifecycleApprovalType? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleoncoreLifecycleApprovalType? result = rawValue == null
                ? null
                : EleoncoreLifecycleApprovalTypeValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreLifecycleApprovalType"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleoncoreLifecycleApprovalType? eleoncoreLifecycleApprovalType, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleoncoreLifecycleApprovalType?.ToString() ?? "null");
        }
    }
}
