// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// Defines EleonsoftSdk.ReportInformationSeverity
    /// </summary>
    public enum EleonsoftSdkReportInformationSeverity
    {
        /// <summary>
        /// Enum Info for value: 0
        /// </summary>
        Info = 0,

        /// <summary>
        /// Enum Warning for value: 1
        /// </summary>
        Warning = 1,

        /// <summary>
        /// Enum Error for value: 2
        /// </summary>
        Error = 2
    }

    /// <summary>
    /// Converts <see cref="EleonsoftSdkReportInformationSeverity"/> to and from the JSON value
    /// </summary>
    public static class EleonsoftSdkReportInformationSeverityValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="EleonsoftSdkReportInformationSeverity"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleonsoftSdkReportInformationSeverity FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return EleonsoftSdkReportInformationSeverity.Info;

            if (value.Equals((1).ToString()))
                return EleonsoftSdkReportInformationSeverity.Warning;

            if (value.Equals((2).ToString()))
                return EleonsoftSdkReportInformationSeverity.Error;

            throw new NotImplementedException($"Could not convert value to type EleonsoftSdkReportInformationSeverity: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="EleonsoftSdkReportInformationSeverity"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleonsoftSdkReportInformationSeverity? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return EleonsoftSdkReportInformationSeverity.Info;

            if (value.Equals((1).ToString()))
                return EleonsoftSdkReportInformationSeverity.Warning;

            if (value.Equals((2).ToString()))
                return EleonsoftSdkReportInformationSeverity.Error;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EleonsoftSdkReportInformationSeverity"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(EleonsoftSdkReportInformationSeverity value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleonsoftSdkReportInformationSeverity"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class EleonsoftSdkReportInformationSeverityJsonConverter : JsonConverter<EleonsoftSdkReportInformationSeverity>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleonsoftSdkReportInformationSeverity Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleonsoftSdkReportInformationSeverity? result = rawValue == null
                ? null
                : EleonsoftSdkReportInformationSeverityValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EleonsoftSdkReportInformationSeverity to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleonsoftSdkReportInformationSeverity"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleonsoftSdkReportInformationSeverity eleonsoftSdkReportInformationSeverity, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleonsoftSdkReportInformationSeverity.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleonsoftSdkReportInformationSeverity"/>
    /// </summary>
    public class EleonsoftSdkReportInformationSeverityNullableJsonConverter : JsonConverter<EleonsoftSdkReportInformationSeverity?>
    {
        /// <summary>
        /// Returns a EleonsoftSdkReportInformationSeverity from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleonsoftSdkReportInformationSeverity? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleonsoftSdkReportInformationSeverity? result = rawValue == null
                ? null
                : EleonsoftSdkReportInformationSeverityValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleonsoftSdkReportInformationSeverity"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleonsoftSdkReportInformationSeverity? eleonsoftSdkReportInformationSeverity, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleonsoftSdkReportInformationSeverity?.ToString() ?? "null");
        }
    }
}
