// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// EleonsoftModuleCollectorHealthCheckDto
    /// </summary>
    public partial class EleonsoftModuleCollectorHealthCheckDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EleonsoftModuleCollectorHealthCheckDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="type">type</param>
        /// <param name="initiatorName">initiatorName</param>
        /// <param name="status">status</param>
        /// <param name="creationTime">creationTime</param>
        [JsonConstructor]
        public EleonsoftModuleCollectorHealthCheckDto(Option<Guid?> id = default, Option<string> type = default, Option<string> initiatorName = default, Option<EleonsoftModuleCollectorHealthCheckStatus?> status = default, Option<DateTime?> creationTime = default)
        {
            IdOption = id;
            TypeOption = type;
            InitiatorNameOption = initiatorName;
            StatusOption = status;
            CreationTimeOption = creationTime;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleonsoftModuleCollectorHealthCheckStatus?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public EleonsoftModuleCollectorHealthCheckStatus? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of InitiatorName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> InitiatorNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets InitiatorName
        /// </summary>
        [JsonPropertyName("initiatorName")]
        public string InitiatorName { get { return this.InitiatorNameOption; } set { this.InitiatorNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of CreationTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CreationTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets CreationTime
        /// </summary>
        [JsonPropertyName("creationTime")]
        public DateTime? CreationTime { get { return this.CreationTimeOption; } set { this.CreationTimeOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EleonsoftModuleCollectorHealthCheckDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  InitiatorName: ").Append(InitiatorName).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  CreationTime: ").Append(CreationTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleonsoftModuleCollectorHealthCheckDto" />
    /// </summary>
    public class EleonsoftModuleCollectorHealthCheckDtoJsonConverter : JsonConverter<EleonsoftModuleCollectorHealthCheckDto>
    {
        /// <summary>
        /// The format to use to serialize CreationTime
        /// </summary>
        public static string CreationTimeFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="EleonsoftModuleCollectorHealthCheckDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EleonsoftModuleCollectorHealthCheckDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string> type = default;
            Option<string> initiatorName = default;
            Option<EleonsoftModuleCollectorHealthCheckStatus?> status = default;
            Option<DateTime?> creationTime = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "type":
                            type = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "initiatorName":
                            initiatorName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "status":
                            string statusRawValue = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<EleonsoftModuleCollectorHealthCheckStatus?>(EleonsoftModuleCollectorHealthCheckStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "creationTime":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                creationTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class EleonsoftModuleCollectorHealthCheckDto.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class EleonsoftModuleCollectorHealthCheckDto.");

            if (creationTime.IsSet && creationTime.Value == null)
                throw new ArgumentNullException(nameof(creationTime), "Property is not nullable for class EleonsoftModuleCollectorHealthCheckDto.");


            return new EleonsoftModuleCollectorHealthCheckDto(id, type, initiatorName, status, creationTime);
        }

        /// <summary>
        /// Serializes a <see cref="EleonsoftModuleCollectorHealthCheckDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleonsoftModuleCollectorHealthCheckDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EleonsoftModuleCollectorHealthCheckDto eleonsoftModuleCollectorHealthCheckDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eleonsoftModuleCollectorHealthCheckDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EleonsoftModuleCollectorHealthCheckDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eleonsoftModuleCollectorHealthCheckDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EleonsoftModuleCollectorHealthCheckDto eleonsoftModuleCollectorHealthCheckDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (eleonsoftModuleCollectorHealthCheckDto.IdOption.IsSet)
    {
        writer.WritePropertyName("id");
        JsonSerializer.Serialize(writer, eleonsoftModuleCollectorHealthCheckDto.Id, jsonSerializerOptions);
    }
    if (eleonsoftModuleCollectorHealthCheckDto.TypeOption.IsSet)
    {
        if (eleonsoftModuleCollectorHealthCheckDto.TypeOption.Value != null)
        {
            writer.WritePropertyName("type");
            JsonSerializer.Serialize(writer, eleonsoftModuleCollectorHealthCheckDto.Type, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("type");
        }
    }
    if (eleonsoftModuleCollectorHealthCheckDto.InitiatorNameOption.IsSet)
    {
        if (eleonsoftModuleCollectorHealthCheckDto.InitiatorNameOption.Value != null)
        {
            writer.WritePropertyName("initiatorName");
            JsonSerializer.Serialize(writer, eleonsoftModuleCollectorHealthCheckDto.InitiatorName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("initiatorName");
        }
    }
    if (eleonsoftModuleCollectorHealthCheckDto.StatusOption.IsSet)
    {
        writer.WritePropertyName("status");
        JsonSerializer.Serialize(writer, eleonsoftModuleCollectorHealthCheckDto.Status, jsonSerializerOptions);
    }
    if (eleonsoftModuleCollectorHealthCheckDto.CreationTimeOption.IsSet)
    {
        writer.WritePropertyName("creationTime");
        JsonSerializer.Serialize(writer, eleonsoftModuleCollectorHealthCheckDto.CreationTime, jsonSerializerOptions);
    }
}

    }
}
