// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// EleonsoftModuleCollectorTenantSystemHealthSettingsDto
    /// </summary>
    public partial class EleonsoftModuleCollectorTenantSystemHealthSettingsDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EleonsoftModuleCollectorTenantSystemHealthSettingsDto" /> class.
        /// </summary>
        /// <param name="telemetry">telemetry</param>
        /// <param name="logging">logging</param>
        [JsonConstructor]
        public EleonsoftModuleCollectorTenantSystemHealthSettingsDto(Option<EleonsoftModuleCollectorTelemetrySettingsDto> telemetry = default, Option<EleonsoftModuleCollectorLoggingSettingsDto> logging = default)
        {
            TelemetryOption = telemetry;
            LoggingOption = logging;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Telemetry
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleonsoftModuleCollectorTelemetrySettingsDto> TelemetryOption { get; private set; }

        /// <summary>
        /// Gets or Sets Telemetry
        /// </summary>
        [JsonPropertyName("telemetry")]
        public EleonsoftModuleCollectorTelemetrySettingsDto Telemetry { get { return this.TelemetryOption; } set { this.TelemetryOption = new(value); } }

        /// <summary>
        /// Used to track the state of Logging
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleonsoftModuleCollectorLoggingSettingsDto> LoggingOption { get; private set; }

        /// <summary>
        /// Gets or Sets Logging
        /// </summary>
        [JsonPropertyName("logging")]
        public EleonsoftModuleCollectorLoggingSettingsDto Logging { get { return this.LoggingOption; } set { this.LoggingOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EleonsoftModuleCollectorTenantSystemHealthSettingsDto {\n");
            sb.Append("  Telemetry: ").Append(Telemetry).Append("\n");
            sb.Append("  Logging: ").Append(Logging).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleonsoftModuleCollectorTenantSystemHealthSettingsDto" />
    /// </summary>
    public class EleonsoftModuleCollectorTenantSystemHealthSettingsDtoJsonConverter : JsonConverter<EleonsoftModuleCollectorTenantSystemHealthSettingsDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="EleonsoftModuleCollectorTenantSystemHealthSettingsDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EleonsoftModuleCollectorTenantSystemHealthSettingsDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<EleonsoftModuleCollectorTelemetrySettingsDto> telemetry = default;
            Option<EleonsoftModuleCollectorLoggingSettingsDto> logging = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "telemetry":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                telemetry = new Option<EleonsoftModuleCollectorTelemetrySettingsDto>(JsonSerializer.Deserialize<EleonsoftModuleCollectorTelemetrySettingsDto>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "logging":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                logging = new Option<EleonsoftModuleCollectorLoggingSettingsDto>(JsonSerializer.Deserialize<EleonsoftModuleCollectorLoggingSettingsDto>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (telemetry.IsSet && telemetry.Value == null)
                throw new ArgumentNullException(nameof(telemetry), "Property is not nullable for class EleonsoftModuleCollectorTenantSystemHealthSettingsDto.");

            if (logging.IsSet && logging.Value == null)
                throw new ArgumentNullException(nameof(logging), "Property is not nullable for class EleonsoftModuleCollectorTenantSystemHealthSettingsDto.");


            return new EleonsoftModuleCollectorTenantSystemHealthSettingsDto(telemetry, logging);
        }

        /// <summary>
        /// Serializes a <see cref="EleonsoftModuleCollectorTenantSystemHealthSettingsDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleonsoftModuleCollectorTenantSystemHealthSettingsDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EleonsoftModuleCollectorTenantSystemHealthSettingsDto eleonsoftModuleCollectorTenantSystemHealthSettingsDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eleonsoftModuleCollectorTenantSystemHealthSettingsDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EleonsoftModuleCollectorTenantSystemHealthSettingsDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eleonsoftModuleCollectorTenantSystemHealthSettingsDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EleonsoftModuleCollectorTenantSystemHealthSettingsDto eleonsoftModuleCollectorTenantSystemHealthSettingsDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (eleonsoftModuleCollectorTenantSystemHealthSettingsDto.TelemetryOption.IsSet)
    {
        writer.WritePropertyName("telemetry");
        JsonSerializer.Serialize(writer, eleonsoftModuleCollectorTenantSystemHealthSettingsDto.Telemetry, jsonSerializerOptions);
    }
    if (eleonsoftModuleCollectorTenantSystemHealthSettingsDto.LoggingOption.IsSet)
    {
        writer.WritePropertyName("logging");
        JsonSerializer.Serialize(writer, eleonsoftModuleCollectorTenantSystemHealthSettingsDto.Logging, jsonSerializerOptions);
    }
}

    }
}
