// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// Defines Eleoncore.AccountStatus
    /// </summary>
    public enum EleoncoreAccountStatus
    {
        /// <summary>
        /// Enum New for value: 0
        /// </summary>
        New = 0,

        /// <summary>
        /// Enum Generating for value: 1
        /// </summary>
        Generating = 1,

        /// <summary>
        /// Enum Active for value: 2
        /// </summary>
        Active = 2,

        /// <summary>
        /// Enum Suspended for value: 3
        /// </summary>
        Suspended = 3,

        /// <summary>
        /// Enum Canceled for value: 4
        /// </summary>
        Canceled = 4,

        /// <summary>
        /// Enum Deleted for value: 5
        /// </summary>
        Deleted = 5
    }

    /// <summary>
    /// Converts <see cref="EleoncoreAccountStatus"/> to and from the JSON value
    /// </summary>
    public static class EleoncoreAccountStatusValueConverter
    {
        /// <summary>
        /// Parses a given value to <see cref="EleoncoreAccountStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleoncoreAccountStatus FromString(string value)
        {
            if (value.Equals((0).ToString()))
                return EleoncoreAccountStatus.New;

            if (value.Equals((1).ToString()))
                return EleoncoreAccountStatus.Generating;

            if (value.Equals((2).ToString()))
                return EleoncoreAccountStatus.Active;

            if (value.Equals((3).ToString()))
                return EleoncoreAccountStatus.Suspended;

            if (value.Equals((4).ToString()))
                return EleoncoreAccountStatus.Canceled;

            if (value.Equals((5).ToString()))
                return EleoncoreAccountStatus.Deleted;

            throw new NotImplementedException($"Could not convert value to type EleoncoreAccountStatus: '{value}'");
        }

        /// <summary>
        /// Parses a given value to <see cref="EleoncoreAccountStatus"/>
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static EleoncoreAccountStatus? FromStringOrDefault(string value)
        {
            if (value.Equals((0).ToString()))
                return EleoncoreAccountStatus.New;

            if (value.Equals((1).ToString()))
                return EleoncoreAccountStatus.Generating;

            if (value.Equals((2).ToString()))
                return EleoncoreAccountStatus.Active;

            if (value.Equals((3).ToString()))
                return EleoncoreAccountStatus.Suspended;

            if (value.Equals((4).ToString()))
                return EleoncoreAccountStatus.Canceled;

            if (value.Equals((5).ToString()))
                return EleoncoreAccountStatus.Deleted;

            return null;
        }

        /// <summary>
        /// Converts the <see cref="EleoncoreAccountStatus"/> to the json value
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        /// <exception cref="NotImplementedException"></exception>
        public static int ToJsonValue(EleoncoreAccountStatus value)
        {
            return (int) value;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreAccountStatus"/>
    /// </summary>
    /// <exception cref="NotImplementedException"></exception>
    public class EleoncoreAccountStatusJsonConverter : JsonConverter<EleoncoreAccountStatus>
    {
        /// <summary>
        /// Returns a  from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleoncoreAccountStatus Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleoncoreAccountStatus? result = rawValue == null
                ? null
                : EleoncoreAccountStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the EleoncoreAccountStatus to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreAccountStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleoncoreAccountStatus eleoncoreAccountStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleoncoreAccountStatus.ToString());
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EleoncoreAccountStatus"/>
    /// </summary>
    public class EleoncoreAccountStatusNullableJsonConverter : JsonConverter<EleoncoreAccountStatus?>
    {
        /// <summary>
        /// Returns a EleoncoreAccountStatus from the Json object
        /// </summary>
        /// <param name="reader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="options"></param>
        /// <returns></returns>
        public override EleoncoreAccountStatus? Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string rawValue = reader.GetString();

            EleoncoreAccountStatus? result = rawValue == null
                ? null
                : EleoncoreAccountStatusValueConverter.FromStringOrDefault(rawValue);

            if (result != null)
                return result.Value;

            throw new JsonException();
        }

        /// <summary>
        /// Writes the DateTime to the json writer
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eleoncoreAccountStatus"></param>
        /// <param name="options"></param>
        public override void Write(Utf8JsonWriter writer, EleoncoreAccountStatus? eleoncoreAccountStatus, JsonSerializerOptions options)
        {
            writer.WriteStringValue(eleoncoreAccountStatus?.ToString() ?? "null");
        }
    }
}
