// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// EventManagementModulePublishMessageRequestDto
    /// </summary>
    public partial class EventManagementModulePublishMessageRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EventManagementModulePublishMessageRequestDto" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="queueName">queueName</param>
        /// <param name="message">message</param>
        [JsonConstructor]
        public EventManagementModulePublishMessageRequestDto(Option<string> name = default, Option<string> queueName = default, Option<string> message = default)
        {
            NameOption = name;
            QueueNameOption = queueName;
            MessageOption = message;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of QueueName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> QueueNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueueName
        /// </summary>
        [JsonPropertyName("queueName")]
        public string QueueName { get { return this.QueueNameOption; } set { this.QueueNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EventManagementModulePublishMessageRequestDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  QueueName: ").Append(QueueName).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="EventManagementModulePublishMessageRequestDto" />
    /// </summary>
    public class EventManagementModulePublishMessageRequestDtoJsonConverter : JsonConverter<EventManagementModulePublishMessageRequestDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="EventManagementModulePublishMessageRequestDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override EventManagementModulePublishMessageRequestDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> name = default;
            Option<string> queueName = default;
            Option<string> message = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "queueName":
                            queueName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "message":
                            message = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }


            return new EventManagementModulePublishMessageRequestDto(name, queueName, message);
        }

        /// <summary>
        /// Serializes a <see cref="EventManagementModulePublishMessageRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="eventManagementModulePublishMessageRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, EventManagementModulePublishMessageRequestDto eventManagementModulePublishMessageRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, eventManagementModulePublishMessageRequestDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="EventManagementModulePublishMessageRequestDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="eventManagementModulePublishMessageRequestDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, EventManagementModulePublishMessageRequestDto eventManagementModulePublishMessageRequestDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (eventManagementModulePublishMessageRequestDto.NameOption.IsSet)
    {
        if (eventManagementModulePublishMessageRequestDto.NameOption.Value != null)
        {
            writer.WritePropertyName("name");
            JsonSerializer.Serialize(writer, eventManagementModulePublishMessageRequestDto.Name, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("name");
        }
    }
    if (eventManagementModulePublishMessageRequestDto.QueueNameOption.IsSet)
    {
        if (eventManagementModulePublishMessageRequestDto.QueueNameOption.Value != null)
        {
            writer.WritePropertyName("queueName");
            JsonSerializer.Serialize(writer, eventManagementModulePublishMessageRequestDto.QueueName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("queueName");
        }
    }
    if (eventManagementModulePublishMessageRequestDto.MessageOption.IsSet)
    {
        if (eventManagementModulePublishMessageRequestDto.MessageOption.Value != null)
        {
            writer.WritePropertyName("message");
            JsonSerializer.Serialize(writer, eventManagementModulePublishMessageRequestDto.Message, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("message");
        }
    }
}

    }
}
