// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// FileManagerFileSourceDto
    /// </summary>
    public partial class FileManagerFileSourceDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileManagerFileSourceDto" /> class.
        /// </summary>
        /// <param name="name">name</param>
        /// <param name="source">source</param>
        /// <param name="type">type</param>
        /// <param name="relativePath">relativePath</param>
        [JsonConstructor]
        public FileManagerFileSourceDto(Option<string> name = default, Option<string> source = default, Option<string> type = default, Option<string> relativePath = default)
        {
            NameOption = name;
            SourceOption = source;
            TypeOption = type;
            RelativePathOption = relativePath;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Source
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> SourceOption { get; private set; }

        /// <summary>
        /// Gets or Sets Source
        /// </summary>
        [JsonPropertyName("source")]
        public string Source { get { return this.SourceOption; } set { this.SourceOption = new(value); } }

        /// <summary>
        /// Used to track the state of Type
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> TypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [JsonPropertyName("type")]
        public string Type { get { return this.TypeOption; } set { this.TypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of RelativePath
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RelativePathOption { get; private set; }

        /// <summary>
        /// Gets or Sets RelativePath
        /// </summary>
        [JsonPropertyName("relativePath")]
        public string RelativePath { get { return this.RelativePathOption; } set { this.RelativePathOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FileManagerFileSourceDto {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Source: ").Append(Source).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  RelativePath: ").Append(RelativePath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FileManagerFileSourceDto" />
    /// </summary>
    public class FileManagerFileSourceDtoJsonConverter : JsonConverter<FileManagerFileSourceDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="FileManagerFileSourceDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FileManagerFileSourceDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> name = default;
            Option<string> source = default;
            Option<string> type = default;
            Option<string> relativePath = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "source":
                            source = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "type":
                            type = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "relativePath":
                            relativePath = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }


            return new FileManagerFileSourceDto(name, source, type, relativePath);
        }

        /// <summary>
        /// Serializes a <see cref="FileManagerFileSourceDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fileManagerFileSourceDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FileManagerFileSourceDto fileManagerFileSourceDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fileManagerFileSourceDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="FileManagerFileSourceDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="fileManagerFileSourceDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, FileManagerFileSourceDto fileManagerFileSourceDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (fileManagerFileSourceDto.NameOption.IsSet)
    {
        if (fileManagerFileSourceDto.NameOption.Value != null)
        {
            writer.WritePropertyName("name");
            JsonSerializer.Serialize(writer, fileManagerFileSourceDto.Name, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("name");
        }
    }
    if (fileManagerFileSourceDto.SourceOption.IsSet)
    {
        if (fileManagerFileSourceDto.SourceOption.Value != null)
        {
            writer.WritePropertyName("source");
            JsonSerializer.Serialize(writer, fileManagerFileSourceDto.Source, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("source");
        }
    }
    if (fileManagerFileSourceDto.TypeOption.IsSet)
    {
        if (fileManagerFileSourceDto.TypeOption.Value != null)
        {
            writer.WritePropertyName("type");
            JsonSerializer.Serialize(writer, fileManagerFileSourceDto.Type, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("type");
        }
    }
    if (fileManagerFileSourceDto.RelativePathOption.IsSet)
    {
        if (fileManagerFileSourceDto.RelativePathOption.Value != null)
        {
            writer.WritePropertyName("relativePath");
            JsonSerializer.Serialize(writer, fileManagerFileSourceDto.RelativePath, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("relativePath");
        }
    }
}

    }
}
