// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// FileManagerFileExternalLinkReviewerDto
    /// </summary>
    public partial class FileManagerFileExternalLinkReviewerDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileManagerFileExternalLinkReviewerDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="reviewerStatus">reviewerStatus</param>
        /// <param name="expirationDateTime">expirationDateTime</param>
        /// <param name="reviewerType">reviewerType</param>
        /// <param name="reviewerKey">reviewerKey</param>
        /// <param name="reviewerKeyLabel">reviewerKeyLabel</param>
        /// <param name="lastReviewDates">lastReviewDates</param>
        /// <param name="externalLinkCode">externalLinkCode</param>
        /// <param name="url">url</param>
        /// <param name="externalLink">externalLink</param>
        [JsonConstructor]
        public FileManagerFileExternalLinkReviewerDto(Option<Guid?> id = default, Option<EleoncoreLinkShareStatus?> reviewerStatus = default, Option<DateTime?> expirationDateTime = default, Option<EleoncoreFileReviewerType?> reviewerType = default, Option<string> reviewerKey = default, Option<string> reviewerKeyLabel = default, Option<DateTime?> lastReviewDates = default, Option<string> externalLinkCode = default, Option<string> url = default, Option<MessagingExternalLinkEto> externalLink = default)
        {
            IdOption = id;
            ReviewerStatusOption = reviewerStatus;
            ExpirationDateTimeOption = expirationDateTime;
            ReviewerTypeOption = reviewerType;
            ReviewerKeyOption = reviewerKey;
            ReviewerKeyLabelOption = reviewerKeyLabel;
            LastReviewDatesOption = lastReviewDates;
            ExternalLinkCodeOption = externalLinkCode;
            UrlOption = url;
            ExternalLinkOption = externalLink;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ReviewerStatus
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleoncoreLinkShareStatus?> ReviewerStatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReviewerStatus
        /// </summary>
        [JsonPropertyName("reviewerStatus")]
        public EleoncoreLinkShareStatus? ReviewerStatus { get { return this.ReviewerStatusOption; } set { this.ReviewerStatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReviewerType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleoncoreFileReviewerType?> ReviewerTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReviewerType
        /// </summary>
        [JsonPropertyName("reviewerType")]
        public EleoncoreFileReviewerType? ReviewerType { get { return this.ReviewerTypeOption; } set { this.ReviewerTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExpirationDateTime
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ExpirationDateTimeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExpirationDateTime
        /// </summary>
        [JsonPropertyName("expirationDateTime")]
        public DateTime? ExpirationDateTime { get { return this.ExpirationDateTimeOption; } set { this.ExpirationDateTimeOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReviewerKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ReviewerKeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReviewerKey
        /// </summary>
        [JsonPropertyName("reviewerKey")]
        public string ReviewerKey { get { return this.ReviewerKeyOption; } set { this.ReviewerKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReviewerKeyLabel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ReviewerKeyLabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReviewerKeyLabel
        /// </summary>
        [JsonPropertyName("reviewerKeyLabel")]
        public string ReviewerKeyLabel { get { return this.ReviewerKeyLabelOption; } set { this.ReviewerKeyLabelOption = new(value); } }

        /// <summary>
        /// Used to track the state of LastReviewDates
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> LastReviewDatesOption { get; private set; }

        /// <summary>
        /// Gets or Sets LastReviewDates
        /// </summary>
        [JsonPropertyName("lastReviewDates")]
        public DateTime? LastReviewDates { get { return this.LastReviewDatesOption; } set { this.LastReviewDatesOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalLinkCode
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ExternalLinkCodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalLinkCode
        /// </summary>
        [JsonPropertyName("externalLinkCode")]
        public string ExternalLinkCode { get { return this.ExternalLinkCodeOption; } set { this.ExternalLinkCodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Url
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> UrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [JsonPropertyName("url")]
        public string Url { get { return this.UrlOption; } set { this.UrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ExternalLink
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<MessagingExternalLinkEto> ExternalLinkOption { get; private set; }

        /// <summary>
        /// Gets or Sets ExternalLink
        /// </summary>
        [JsonPropertyName("externalLink")]
        public MessagingExternalLinkEto ExternalLink { get { return this.ExternalLinkOption; } set { this.ExternalLinkOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FileManagerFileExternalLinkReviewerDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ReviewerStatus: ").Append(ReviewerStatus).Append("\n");
            sb.Append("  ExpirationDateTime: ").Append(ExpirationDateTime).Append("\n");
            sb.Append("  ReviewerType: ").Append(ReviewerType).Append("\n");
            sb.Append("  ReviewerKey: ").Append(ReviewerKey).Append("\n");
            sb.Append("  ReviewerKeyLabel: ").Append(ReviewerKeyLabel).Append("\n");
            sb.Append("  LastReviewDates: ").Append(LastReviewDates).Append("\n");
            sb.Append("  ExternalLinkCode: ").Append(ExternalLinkCode).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  ExternalLink: ").Append(ExternalLink).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FileManagerFileExternalLinkReviewerDto" />
    /// </summary>
    public class FileManagerFileExternalLinkReviewerDtoJsonConverter : JsonConverter<FileManagerFileExternalLinkReviewerDto>
    {
        /// <summary>
        /// The format to use to serialize ExpirationDateTime
        /// </summary>
        public static string ExpirationDateTimeFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize LastReviewDates
        /// </summary>
        public static string LastReviewDatesFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="FileManagerFileExternalLinkReviewerDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FileManagerFileExternalLinkReviewerDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<EleoncoreLinkShareStatus?> reviewerStatus = default;
            Option<DateTime?> expirationDateTime = default;
            Option<EleoncoreFileReviewerType?> reviewerType = default;
            Option<string> reviewerKey = default;
            Option<string> reviewerKeyLabel = default;
            Option<DateTime?> lastReviewDates = default;
            Option<string> externalLinkCode = default;
            Option<string> url = default;
            Option<MessagingExternalLinkEto> externalLink = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "reviewerStatus":
                            string reviewerStatusRawValue = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                            if (reviewerStatusRawValue != null)
                                reviewerStatus = new Option<EleoncoreLinkShareStatus?>(EleoncoreLinkShareStatusValueConverter.FromStringOrDefault(reviewerStatusRawValue));
                            break;
                        case "expirationDateTime":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                expirationDateTime = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "reviewerType":
                            string reviewerTypeRawValue = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                            if (reviewerTypeRawValue != null)
                                reviewerType = new Option<EleoncoreFileReviewerType?>(EleoncoreFileReviewerTypeValueConverter.FromStringOrDefault(reviewerTypeRawValue));
                            break;
                        case "reviewerKey":
                            reviewerKey = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "reviewerKeyLabel":
                            reviewerKeyLabel = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "lastReviewDates":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                lastReviewDates = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "externalLinkCode":
                            externalLinkCode = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "url":
                            url = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "externalLink":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                externalLink = new Option<MessagingExternalLinkEto>(JsonSerializer.Deserialize<MessagingExternalLinkEto>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class FileManagerFileExternalLinkReviewerDto.");

            if (reviewerStatus.IsSet && reviewerStatus.Value == null)
                throw new ArgumentNullException(nameof(reviewerStatus), "Property is not nullable for class FileManagerFileExternalLinkReviewerDto.");

            if (expirationDateTime.IsSet && expirationDateTime.Value == null)
                throw new ArgumentNullException(nameof(expirationDateTime), "Property is not nullable for class FileManagerFileExternalLinkReviewerDto.");

            if (reviewerType.IsSet && reviewerType.Value == null)
                throw new ArgumentNullException(nameof(reviewerType), "Property is not nullable for class FileManagerFileExternalLinkReviewerDto.");

            if (lastReviewDates.IsSet && lastReviewDates.Value == null)
                throw new ArgumentNullException(nameof(lastReviewDates), "Property is not nullable for class FileManagerFileExternalLinkReviewerDto.");

            if (externalLink.IsSet && externalLink.Value == null)
                throw new ArgumentNullException(nameof(externalLink), "Property is not nullable for class FileManagerFileExternalLinkReviewerDto.");


            return new FileManagerFileExternalLinkReviewerDto(id, reviewerStatus, expirationDateTime, reviewerType, reviewerKey, reviewerKeyLabel, lastReviewDates, externalLinkCode, url, externalLink);
        }

        /// <summary>
        /// Serializes a <see cref="FileManagerFileExternalLinkReviewerDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fileManagerFileExternalLinkReviewerDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FileManagerFileExternalLinkReviewerDto fileManagerFileExternalLinkReviewerDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fileManagerFileExternalLinkReviewerDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="FileManagerFileExternalLinkReviewerDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="fileManagerFileExternalLinkReviewerDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, FileManagerFileExternalLinkReviewerDto fileManagerFileExternalLinkReviewerDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (fileManagerFileExternalLinkReviewerDto.IdOption.IsSet)
    {
        writer.WritePropertyName("id");
        JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.Id, jsonSerializerOptions);
    }
    if (fileManagerFileExternalLinkReviewerDto.ReviewerStatusOption.IsSet)
    {
        writer.WritePropertyName("reviewerStatus");
        JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.ReviewerStatus, jsonSerializerOptions);
    }
    if (fileManagerFileExternalLinkReviewerDto.ExpirationDateTimeOption.IsSet)
    {
        writer.WritePropertyName("expirationDateTime");
        JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.ExpirationDateTime, jsonSerializerOptions);
    }
    if (fileManagerFileExternalLinkReviewerDto.ReviewerTypeOption.IsSet)
    {
        writer.WritePropertyName("reviewerType");
        JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.ReviewerType, jsonSerializerOptions);
    }
    if (fileManagerFileExternalLinkReviewerDto.ReviewerKeyOption.IsSet)
    {
        if (fileManagerFileExternalLinkReviewerDto.ReviewerKeyOption.Value != null)
        {
            writer.WritePropertyName("reviewerKey");
            JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.ReviewerKey, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("reviewerKey");
        }
    }
    if (fileManagerFileExternalLinkReviewerDto.ReviewerKeyLabelOption.IsSet)
    {
        if (fileManagerFileExternalLinkReviewerDto.ReviewerKeyLabelOption.Value != null)
        {
            writer.WritePropertyName("reviewerKeyLabel");
            JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.ReviewerKeyLabel, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("reviewerKeyLabel");
        }
    }
    if (fileManagerFileExternalLinkReviewerDto.LastReviewDatesOption.IsSet)
    {
        writer.WritePropertyName("lastReviewDates");
        JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.LastReviewDates, jsonSerializerOptions);
    }
    if (fileManagerFileExternalLinkReviewerDto.ExternalLinkCodeOption.IsSet)
    {
        if (fileManagerFileExternalLinkReviewerDto.ExternalLinkCodeOption.Value != null)
        {
            writer.WritePropertyName("externalLinkCode");
            JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.ExternalLinkCode, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("externalLinkCode");
        }
    }
    if (fileManagerFileExternalLinkReviewerDto.UrlOption.IsSet)
    {
        if (fileManagerFileExternalLinkReviewerDto.UrlOption.Value != null)
        {
            writer.WritePropertyName("url");
            JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.Url, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("url");
        }
    }
    if (fileManagerFileExternalLinkReviewerDto.ExternalLinkOption.IsSet)
    {
        writer.WritePropertyName("externalLink");
        JsonSerializer.Serialize(writer, fileManagerFileExternalLinkReviewerDto.ExternalLink, jsonSerializerOptions);
    }
}

    }
}
