// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// FileManagerFileArchiveDto
    /// </summary>
    public partial class FileManagerFileArchiveDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FileManagerFileArchiveDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="rootFolderId">rootFolderId</param>
        /// <param name="physicalRootFolderId">physicalRootFolderId</param>
        /// <param name="fileArchiveHierarchyType">fileArchiveHierarchyType</param>
        /// <param name="storageProviderId">storageProviderId</param>
        /// <param name="fileEditStorageProviderId">fileEditStorageProviderId</param>
        /// <param name="storageProviderName">storageProviderName</param>
        /// <param name="isActive">isActive</param>
        /// <param name="isPersonalizedArchive">isPersonalizedArchive</param>
        [JsonConstructor]
        public FileManagerFileArchiveDto(Option<Guid?> id = default, Option<string> name = default, Option<string> rootFolderId = default, Option<string> physicalRootFolderId = default, Option<EleoncoreFileArchiveHierarchyType?> fileArchiveHierarchyType = default, Option<Guid?> storageProviderId = default, Option<Guid?> fileEditStorageProviderId = default, Option<string> storageProviderName = default, Option<bool?> isActive = default, Option<bool?> isPersonalizedArchive = default)
        {
            IdOption = id;
            NameOption = name;
            RootFolderIdOption = rootFolderId;
            PhysicalRootFolderIdOption = physicalRootFolderId;
            FileArchiveHierarchyTypeOption = fileArchiveHierarchyType;
            StorageProviderIdOption = storageProviderId;
            FileEditStorageProviderIdOption = fileEditStorageProviderId;
            StorageProviderNameOption = storageProviderName;
            IsActiveOption = isActive;
            IsPersonalizedArchiveOption = isPersonalizedArchive;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of FileArchiveHierarchyType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleoncoreFileArchiveHierarchyType?> FileArchiveHierarchyTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets FileArchiveHierarchyType
        /// </summary>
        [JsonPropertyName("fileArchiveHierarchyType")]
        public EleoncoreFileArchiveHierarchyType? FileArchiveHierarchyType { get { return this.FileArchiveHierarchyTypeOption; } set { this.FileArchiveHierarchyTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of RootFolderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> RootFolderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets RootFolderId
        /// </summary>
        [JsonPropertyName("rootFolderId")]
        public string RootFolderId { get { return this.RootFolderIdOption; } set { this.RootFolderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of PhysicalRootFolderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PhysicalRootFolderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets PhysicalRootFolderId
        /// </summary>
        [JsonPropertyName("physicalRootFolderId")]
        public string PhysicalRootFolderId { get { return this.PhysicalRootFolderIdOption; } set { this.PhysicalRootFolderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of StorageProviderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> StorageProviderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets StorageProviderId
        /// </summary>
        [JsonPropertyName("storageProviderId")]
        public Guid? StorageProviderId { get { return this.StorageProviderIdOption; } set { this.StorageProviderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FileEditStorageProviderId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> FileEditStorageProviderIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets FileEditStorageProviderId
        /// </summary>
        [JsonPropertyName("fileEditStorageProviderId")]
        public Guid? FileEditStorageProviderId { get { return this.FileEditStorageProviderIdOption; } set { this.FileEditStorageProviderIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of StorageProviderName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> StorageProviderNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets StorageProviderName
        /// </summary>
        [JsonPropertyName("storageProviderName")]
        public string StorageProviderName { get { return this.StorageProviderNameOption; } set { this.StorageProviderNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsActive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsActive
        /// </summary>
        [JsonPropertyName("isActive")]
        public bool? IsActive { get { return this.IsActiveOption; } set { this.IsActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsPersonalizedArchive
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsPersonalizedArchiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsPersonalizedArchive
        /// </summary>
        [JsonPropertyName("isPersonalizedArchive")]
        public bool? IsPersonalizedArchive { get { return this.IsPersonalizedArchiveOption; } set { this.IsPersonalizedArchiveOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FileManagerFileArchiveDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  RootFolderId: ").Append(RootFolderId).Append("\n");
            sb.Append("  PhysicalRootFolderId: ").Append(PhysicalRootFolderId).Append("\n");
            sb.Append("  FileArchiveHierarchyType: ").Append(FileArchiveHierarchyType).Append("\n");
            sb.Append("  StorageProviderId: ").Append(StorageProviderId).Append("\n");
            sb.Append("  FileEditStorageProviderId: ").Append(FileEditStorageProviderId).Append("\n");
            sb.Append("  StorageProviderName: ").Append(StorageProviderName).Append("\n");
            sb.Append("  IsActive: ").Append(IsActive).Append("\n");
            sb.Append("  IsPersonalizedArchive: ").Append(IsPersonalizedArchive).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FileManagerFileArchiveDto" />
    /// </summary>
    public class FileManagerFileArchiveDtoJsonConverter : JsonConverter<FileManagerFileArchiveDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="FileManagerFileArchiveDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FileManagerFileArchiveDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string> name = default;
            Option<string> rootFolderId = default;
            Option<string> physicalRootFolderId = default;
            Option<EleoncoreFileArchiveHierarchyType?> fileArchiveHierarchyType = default;
            Option<Guid?> storageProviderId = default;
            Option<Guid?> fileEditStorageProviderId = default;
            Option<string> storageProviderName = default;
            Option<bool?> isActive = default;
            Option<bool?> isPersonalizedArchive = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "rootFolderId":
                            rootFolderId = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "physicalRootFolderId":
                            physicalRootFolderId = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "fileArchiveHierarchyType":
                            string fileArchiveHierarchyTypeRawValue = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                            if (fileArchiveHierarchyTypeRawValue != null)
                                fileArchiveHierarchyType = new Option<EleoncoreFileArchiveHierarchyType?>(EleoncoreFileArchiveHierarchyTypeValueConverter.FromStringOrDefault(fileArchiveHierarchyTypeRawValue));
                            break;
                        case "storageProviderId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                storageProviderId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "fileEditStorageProviderId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                fileEditStorageProviderId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "storageProviderName":
                            storageProviderName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "isActive":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isActive = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "isPersonalizedArchive":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isPersonalizedArchive = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class FileManagerFileArchiveDto.");

            if (fileArchiveHierarchyType.IsSet && fileArchiveHierarchyType.Value == null)
                throw new ArgumentNullException(nameof(fileArchiveHierarchyType), "Property is not nullable for class FileManagerFileArchiveDto.");

            if (storageProviderId.IsSet && storageProviderId.Value == null)
                throw new ArgumentNullException(nameof(storageProviderId), "Property is not nullable for class FileManagerFileArchiveDto.");

            if (fileEditStorageProviderId.IsSet && fileEditStorageProviderId.Value == null)
                throw new ArgumentNullException(nameof(fileEditStorageProviderId), "Property is not nullable for class FileManagerFileArchiveDto.");

            if (isActive.IsSet && isActive.Value == null)
                throw new ArgumentNullException(nameof(isActive), "Property is not nullable for class FileManagerFileArchiveDto.");

            if (isPersonalizedArchive.IsSet && isPersonalizedArchive.Value == null)
                throw new ArgumentNullException(nameof(isPersonalizedArchive), "Property is not nullable for class FileManagerFileArchiveDto.");


            return new FileManagerFileArchiveDto(id, name, rootFolderId, physicalRootFolderId, fileArchiveHierarchyType, storageProviderId, fileEditStorageProviderId, storageProviderName, isActive, isPersonalizedArchive);
        }

        /// <summary>
        /// Serializes a <see cref="FileManagerFileArchiveDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fileManagerFileArchiveDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FileManagerFileArchiveDto fileManagerFileArchiveDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fileManagerFileArchiveDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="FileManagerFileArchiveDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="fileManagerFileArchiveDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, FileManagerFileArchiveDto fileManagerFileArchiveDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (fileManagerFileArchiveDto.IdOption.IsSet)
    {
        writer.WritePropertyName("id");
        JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.Id, jsonSerializerOptions);
    }
    if (fileManagerFileArchiveDto.NameOption.IsSet)
    {
        if (fileManagerFileArchiveDto.NameOption.Value != null)
        {
            writer.WritePropertyName("name");
            JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.Name, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("name");
        }
    }
    if (fileManagerFileArchiveDto.RootFolderIdOption.IsSet)
    {
        if (fileManagerFileArchiveDto.RootFolderIdOption.Value != null)
        {
            writer.WritePropertyName("rootFolderId");
            JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.RootFolderId, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("rootFolderId");
        }
    }
    if (fileManagerFileArchiveDto.PhysicalRootFolderIdOption.IsSet)
    {
        if (fileManagerFileArchiveDto.PhysicalRootFolderIdOption.Value != null)
        {
            writer.WritePropertyName("physicalRootFolderId");
            JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.PhysicalRootFolderId, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("physicalRootFolderId");
        }
    }
    if (fileManagerFileArchiveDto.FileArchiveHierarchyTypeOption.IsSet)
    {
        writer.WritePropertyName("fileArchiveHierarchyType");
        JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.FileArchiveHierarchyType, jsonSerializerOptions);
    }
    if (fileManagerFileArchiveDto.StorageProviderIdOption.IsSet)
    {
        writer.WritePropertyName("storageProviderId");
        JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.StorageProviderId, jsonSerializerOptions);
    }
    if (fileManagerFileArchiveDto.FileEditStorageProviderIdOption.IsSet)
    {
        writer.WritePropertyName("fileEditStorageProviderId");
        JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.FileEditStorageProviderId, jsonSerializerOptions);
    }
    if (fileManagerFileArchiveDto.StorageProviderNameOption.IsSet)
    {
        if (fileManagerFileArchiveDto.StorageProviderNameOption.Value != null)
        {
            writer.WritePropertyName("storageProviderName");
            JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.StorageProviderName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("storageProviderName");
        }
    }
    if (fileManagerFileArchiveDto.IsActiveOption.IsSet)
    {
        writer.WritePropertyName("isActive");
        JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.IsActive, jsonSerializerOptions);
    }
    if (fileManagerFileArchiveDto.IsPersonalizedArchiveOption.IsSet)
    {
        writer.WritePropertyName("isPersonalizedArchive");
        JsonSerializer.Serialize(writer, fileManagerFileArchiveDto.IsPersonalizedArchive, jsonSerializerOptions);
    }
}

    }
}
