// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// JobSchedulerActionExecutionDto
    /// </summary>
    public partial class JobSchedulerActionExecutionDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="JobSchedulerActionExecutionDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="status">status</param>
        /// <param name="jobId">jobId</param>
        /// <param name="parentActionExecutionIds">parentActionExecutionIds</param>
        /// <param name="eventName">eventName</param>
        /// <param name="actionName">actionName</param>
        /// <param name="startedAtUtc">startedAtUtc</param>
        /// <param name="completedAtUtc">completedAtUtc</param>
        /// <param name="statusChangedBy">statusChangedBy</param>
        /// <param name="isStatusChangedManually">isStatusChangedManually</param>
        [JsonConstructor]
        public JobSchedulerActionExecutionDto(Option<Guid?> id = default, Option<EleoncoreJobSchedulerActionExecutionStatus?> status = default, Option<Guid?> jobId = default, Option<List<Guid>> parentActionExecutionIds = default, Option<string> eventName = default, Option<string> actionName = default, Option<DateTime?> startedAtUtc = default, Option<DateTime?> completedAtUtc = default, Option<string> statusChangedBy = default, Option<bool?> isStatusChangedManually = default)
        {
            IdOption = id;
            StatusOption = status;
            JobIdOption = jobId;
            ParentActionExecutionIdsOption = parentActionExecutionIds;
            EventNameOption = eventName;
            ActionNameOption = actionName;
            StartedAtUtcOption = startedAtUtc;
            CompletedAtUtcOption = completedAtUtc;
            StatusChangedByOption = statusChangedBy;
            IsStatusChangedManuallyOption = isStatusChangedManually;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Status
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleoncoreJobSchedulerActionExecutionStatus?> StatusOption { get; private set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public EleoncoreJobSchedulerActionExecutionStatus? Status { get { return this.StatusOption; } set { this.StatusOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of JobId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> JobIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets JobId
        /// </summary>
        [JsonPropertyName("jobId")]
        public Guid? JobId { get { return this.JobIdOption; } set { this.JobIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ParentActionExecutionIds
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<Guid>> ParentActionExecutionIdsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParentActionExecutionIds
        /// </summary>
        [JsonPropertyName("parentActionExecutionIds")]
        public List<Guid> ParentActionExecutionIds { get { return this.ParentActionExecutionIdsOption; } set { this.ParentActionExecutionIdsOption = new(value); } }

        /// <summary>
        /// Used to track the state of EventName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> EventNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets EventName
        /// </summary>
        [JsonPropertyName("eventName")]
        public string EventName { get { return this.EventNameOption; } set { this.EventNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ActionName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ActionNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActionName
        /// </summary>
        [JsonPropertyName("actionName")]
        public string ActionName { get { return this.ActionNameOption; } set { this.ActionNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of StartedAtUtc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> StartedAtUtcOption { get; private set; }

        /// <summary>
        /// Gets or Sets StartedAtUtc
        /// </summary>
        [JsonPropertyName("startedAtUtc")]
        public DateTime? StartedAtUtc { get { return this.StartedAtUtcOption; } set { this.StartedAtUtcOption = new(value); } }

        /// <summary>
        /// Used to track the state of CompletedAtUtc
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> CompletedAtUtcOption { get; private set; }

        /// <summary>
        /// Gets or Sets CompletedAtUtc
        /// </summary>
        [JsonPropertyName("completedAtUtc")]
        public DateTime? CompletedAtUtc { get { return this.CompletedAtUtcOption; } set { this.CompletedAtUtcOption = new(value); } }

        /// <summary>
        /// Used to track the state of StatusChangedBy
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> StatusChangedByOption { get; private set; }

        /// <summary>
        /// Gets or Sets StatusChangedBy
        /// </summary>
        [JsonPropertyName("statusChangedBy")]
        public string StatusChangedBy { get { return this.StatusChangedByOption; } set { this.StatusChangedByOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsStatusChangedManually
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsStatusChangedManuallyOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsStatusChangedManually
        /// </summary>
        [JsonPropertyName("isStatusChangedManually")]
        public bool? IsStatusChangedManually { get { return this.IsStatusChangedManuallyOption; } set { this.IsStatusChangedManuallyOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class JobSchedulerActionExecutionDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  JobId: ").Append(JobId).Append("\n");
            sb.Append("  ParentActionExecutionIds: ").Append(ParentActionExecutionIds).Append("\n");
            sb.Append("  EventName: ").Append(EventName).Append("\n");
            sb.Append("  ActionName: ").Append(ActionName).Append("\n");
            sb.Append("  StartedAtUtc: ").Append(StartedAtUtc).Append("\n");
            sb.Append("  CompletedAtUtc: ").Append(CompletedAtUtc).Append("\n");
            sb.Append("  StatusChangedBy: ").Append(StatusChangedBy).Append("\n");
            sb.Append("  IsStatusChangedManually: ").Append(IsStatusChangedManually).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="JobSchedulerActionExecutionDto" />
    /// </summary>
    public class JobSchedulerActionExecutionDtoJsonConverter : JsonConverter<JobSchedulerActionExecutionDto>
    {
        /// <summary>
        /// The format to use to serialize StartedAtUtc
        /// </summary>
        public static string StartedAtUtcFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize CompletedAtUtc
        /// </summary>
        public static string CompletedAtUtcFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="JobSchedulerActionExecutionDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override JobSchedulerActionExecutionDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<EleoncoreJobSchedulerActionExecutionStatus?> status = default;
            Option<Guid?> jobId = default;
            Option<List<Guid>> parentActionExecutionIds = default;
            Option<string> eventName = default;
            Option<string> actionName = default;
            Option<DateTime?> startedAtUtc = default;
            Option<DateTime?> completedAtUtc = default;
            Option<string> statusChangedBy = default;
            Option<bool?> isStatusChangedManually = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "status":
                            string statusRawValue = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                            if (statusRawValue != null)
                                status = new Option<EleoncoreJobSchedulerActionExecutionStatus?>(EleoncoreJobSchedulerActionExecutionStatusValueConverter.FromStringOrDefault(statusRawValue));
                            break;
                        case "jobId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                jobId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "parentActionExecutionIds":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                parentActionExecutionIds = new Option<List<Guid>>(JsonSerializer.Deserialize<List<Guid>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "eventName":
                            eventName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "actionName":
                            actionName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "startedAtUtc":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                startedAtUtc = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "completedAtUtc":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                completedAtUtc = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "statusChangedBy":
                            statusChangedBy = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "isStatusChangedManually":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isStatusChangedManually = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class JobSchedulerActionExecutionDto.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class JobSchedulerActionExecutionDto.");

            if (isStatusChangedManually.IsSet && isStatusChangedManually.Value == null)
                throw new ArgumentNullException(nameof(isStatusChangedManually), "Property is not nullable for class JobSchedulerActionExecutionDto.");


            return new JobSchedulerActionExecutionDto(id, status, jobId, parentActionExecutionIds, eventName, actionName, startedAtUtc, completedAtUtc, statusChangedBy, isStatusChangedManually);
        }

        /// <summary>
        /// Serializes a <see cref="JobSchedulerActionExecutionDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="jobSchedulerActionExecutionDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, JobSchedulerActionExecutionDto jobSchedulerActionExecutionDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, jobSchedulerActionExecutionDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="JobSchedulerActionExecutionDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="jobSchedulerActionExecutionDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, JobSchedulerActionExecutionDto jobSchedulerActionExecutionDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (jobSchedulerActionExecutionDto.IdOption.IsSet)
    {
        writer.WritePropertyName("id");
        JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.Id, jsonSerializerOptions);
    }
    if (jobSchedulerActionExecutionDto.StatusOption.IsSet)
    {
        writer.WritePropertyName("status");
        JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.Status, jsonSerializerOptions);
    }
    if (jobSchedulerActionExecutionDto.JobIdOption.IsSet)
    {
        if (jobSchedulerActionExecutionDto.JobIdOption.Value != null)
        {
            writer.WritePropertyName("jobId");
            JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.JobId, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("jobId");
        }
    }
    if (jobSchedulerActionExecutionDto.ParentActionExecutionIdsOption.IsSet)
    {
        if (jobSchedulerActionExecutionDto.ParentActionExecutionIdsOption.Value != null)
        {
            writer.WritePropertyName("parentActionExecutionIds");
            JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.ParentActionExecutionIds, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("parentActionExecutionIds");
        }
    }
    if (jobSchedulerActionExecutionDto.EventNameOption.IsSet)
    {
        if (jobSchedulerActionExecutionDto.EventNameOption.Value != null)
        {
            writer.WritePropertyName("eventName");
            JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.EventName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("eventName");
        }
    }
    if (jobSchedulerActionExecutionDto.ActionNameOption.IsSet)
    {
        if (jobSchedulerActionExecutionDto.ActionNameOption.Value != null)
        {
            writer.WritePropertyName("actionName");
            JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.ActionName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("actionName");
        }
    }
    if (jobSchedulerActionExecutionDto.StartedAtUtcOption.IsSet)
    {
        if (jobSchedulerActionExecutionDto.StartedAtUtcOption.Value != null)
        {
            writer.WritePropertyName("startedAtUtc");
            JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.StartedAtUtc, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("startedAtUtc");
        }
    }
    if (jobSchedulerActionExecutionDto.CompletedAtUtcOption.IsSet)
    {
        if (jobSchedulerActionExecutionDto.CompletedAtUtcOption.Value != null)
        {
            writer.WritePropertyName("completedAtUtc");
            JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.CompletedAtUtc, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("completedAtUtc");
        }
    }
    if (jobSchedulerActionExecutionDto.StatusChangedByOption.IsSet)
    {
        if (jobSchedulerActionExecutionDto.StatusChangedByOption.Value != null)
        {
            writer.WritePropertyName("statusChangedBy");
            JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.StatusChangedBy, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("statusChangedBy");
        }
    }
    if (jobSchedulerActionExecutionDto.IsStatusChangedManuallyOption.IsSet)
    {
        writer.WritePropertyName("isStatusChangedManually");
        JsonSerializer.Serialize(writer, jobSchedulerActionExecutionDto.IsStatusChangedManually, jsonSerializerOptions);
    }
}

    }
}
