// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// LanguageManagementOverrideLocalizationEntryRequest
    /// </summary>
    public partial class LanguageManagementOverrideLocalizationEntryRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LanguageManagementOverrideLocalizationEntryRequest" /> class.
        /// </summary>
        /// <param name="resourceName">resourceName</param>
        /// <param name="key">key</param>
        /// <param name="cultureName">cultureName</param>
        /// <param name="newValue">newValue</param>
        [JsonConstructor]
        public LanguageManagementOverrideLocalizationEntryRequest(Option<string> resourceName = default, Option<string> key = default, Option<string> cultureName = default, Option<string> newValue = default)
        {
            ResourceNameOption = resourceName;
            KeyOption = key;
            CultureNameOption = cultureName;
            NewValueOption = newValue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ResourceName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ResourceNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ResourceName
        /// </summary>
        [JsonPropertyName("resourceName")]
        public string ResourceName { get { return this.ResourceNameOption; } set { this.ResourceNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Key
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> KeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets Key
        /// </summary>
        [JsonPropertyName("key")]
        public string Key { get { return this.KeyOption; } set { this.KeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of CultureName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CultureNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets CultureName
        /// </summary>
        [JsonPropertyName("cultureName")]
        public string CultureName { get { return this.CultureNameOption; } set { this.CultureNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewValue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NewValueOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewValue
        /// </summary>
        [JsonPropertyName("newValue")]
        public string NewValue { get { return this.NewValueOption; } set { this.NewValueOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LanguageManagementOverrideLocalizationEntryRequest {\n");
            sb.Append("  ResourceName: ").Append(ResourceName).Append("\n");
            sb.Append("  Key: ").Append(Key).Append("\n");
            sb.Append("  CultureName: ").Append(CultureName).Append("\n");
            sb.Append("  NewValue: ").Append(NewValue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LanguageManagementOverrideLocalizationEntryRequest" />
    /// </summary>
    public class LanguageManagementOverrideLocalizationEntryRequestJsonConverter : JsonConverter<LanguageManagementOverrideLocalizationEntryRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="LanguageManagementOverrideLocalizationEntryRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LanguageManagementOverrideLocalizationEntryRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string> resourceName = default;
            Option<string> key = default;
            Option<string> cultureName = default;
            Option<string> newValue = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "resourceName":
                            resourceName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "key":
                            key = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "cultureName":
                            cultureName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "newValue":
                            newValue = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }


            return new LanguageManagementOverrideLocalizationEntryRequest(resourceName, key, cultureName, newValue);
        }

        /// <summary>
        /// Serializes a <see cref="LanguageManagementOverrideLocalizationEntryRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="languageManagementOverrideLocalizationEntryRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LanguageManagementOverrideLocalizationEntryRequest languageManagementOverrideLocalizationEntryRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, languageManagementOverrideLocalizationEntryRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="LanguageManagementOverrideLocalizationEntryRequest" />
/// </summary>
/// <param name="writer"></param>
/// <param name="languageManagementOverrideLocalizationEntryRequest"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, LanguageManagementOverrideLocalizationEntryRequest languageManagementOverrideLocalizationEntryRequest, JsonSerializerOptions jsonSerializerOptions)
{
    if (languageManagementOverrideLocalizationEntryRequest.ResourceNameOption.IsSet)
    {
        if (languageManagementOverrideLocalizationEntryRequest.ResourceNameOption.Value != null)
        {
            writer.WritePropertyName("resourceName");
            JsonSerializer.Serialize(writer, languageManagementOverrideLocalizationEntryRequest.ResourceName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("resourceName");
        }
    }
    if (languageManagementOverrideLocalizationEntryRequest.KeyOption.IsSet)
    {
        if (languageManagementOverrideLocalizationEntryRequest.KeyOption.Value != null)
        {
            writer.WritePropertyName("key");
            JsonSerializer.Serialize(writer, languageManagementOverrideLocalizationEntryRequest.Key, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("key");
        }
    }
    if (languageManagementOverrideLocalizationEntryRequest.CultureNameOption.IsSet)
    {
        if (languageManagementOverrideLocalizationEntryRequest.CultureNameOption.Value != null)
        {
            writer.WritePropertyName("cultureName");
            JsonSerializer.Serialize(writer, languageManagementOverrideLocalizationEntryRequest.CultureName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("cultureName");
        }
    }
    if (languageManagementOverrideLocalizationEntryRequest.NewValueOption.IsSet)
    {
        if (languageManagementOverrideLocalizationEntryRequest.NewValueOption.Value != null)
        {
            writer.WritePropertyName("newValue");
            JsonSerializer.Serialize(writer, languageManagementOverrideLocalizationEntryRequest.NewValue, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("newValue");
        }
    }
}

    }
}
