// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// LifecycleConditionDto
    /// </summary>
    public partial class LifecycleConditionDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LifecycleConditionDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="conditionType">conditionType</param>
        /// <param name="refId">refId</param>
        /// <param name="rules">rules</param>
        [JsonConstructor]
        public LifecycleConditionDto(Option<Guid?> id = default, Option<EleoncoreLifecycleConditionTargetType?> conditionType = default, Option<Guid?> refId = default, Option<List<LifecycleRuleDto>> rules = default)
        {
            IdOption = id;
            ConditionTypeOption = conditionType;
            RefIdOption = refId;
            RulesOption = rules;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of ConditionType
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<EleoncoreLifecycleConditionTargetType?> ConditionTypeOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConditionType
        /// </summary>
        [JsonPropertyName("conditionType")]
        public EleoncoreLifecycleConditionTargetType? ConditionType { get { return this.ConditionTypeOption; } set { this.ConditionTypeOption = new(value); } }

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of RefId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> RefIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets RefId
        /// </summary>
        [JsonPropertyName("refId")]
        public Guid? RefId { get { return this.RefIdOption; } set { this.RefIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Rules
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<LifecycleRuleDto>> RulesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Rules
        /// </summary>
        [JsonPropertyName("rules")]
        public List<LifecycleRuleDto> Rules { get { return this.RulesOption; } set { this.RulesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LifecycleConditionDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  ConditionType: ").Append(ConditionType).Append("\n");
            sb.Append("  RefId: ").Append(RefId).Append("\n");
            sb.Append("  Rules: ").Append(Rules).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="LifecycleConditionDto" />
    /// </summary>
    public class LifecycleConditionDtoJsonConverter : JsonConverter<LifecycleConditionDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="LifecycleConditionDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override LifecycleConditionDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<EleoncoreLifecycleConditionTargetType?> conditionType = default;
            Option<Guid?> refId = default;
            Option<List<LifecycleRuleDto>> rules = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "conditionType":
                            string conditionTypeRawValue = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                            if (conditionTypeRawValue != null)
                                conditionType = new Option<EleoncoreLifecycleConditionTargetType?>(EleoncoreLifecycleConditionTargetTypeValueConverter.FromStringOrDefault(conditionTypeRawValue));
                            break;
                        case "refId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                refId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "rules":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                rules = new Option<List<LifecycleRuleDto>>(JsonSerializer.Deserialize<List<LifecycleRuleDto>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class LifecycleConditionDto.");

            if (conditionType.IsSet && conditionType.Value == null)
                throw new ArgumentNullException(nameof(conditionType), "Property is not nullable for class LifecycleConditionDto.");

            if (refId.IsSet && refId.Value == null)
                throw new ArgumentNullException(nameof(refId), "Property is not nullable for class LifecycleConditionDto.");


            return new LifecycleConditionDto(id, conditionType, refId, rules);
        }

        /// <summary>
        /// Serializes a <see cref="LifecycleConditionDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="lifecycleConditionDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, LifecycleConditionDto lifecycleConditionDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, lifecycleConditionDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="LifecycleConditionDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="lifecycleConditionDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, LifecycleConditionDto lifecycleConditionDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (lifecycleConditionDto.IdOption.IsSet)
    {
        writer.WritePropertyName("id");
        JsonSerializer.Serialize(writer, lifecycleConditionDto.Id, jsonSerializerOptions);
    }
    if (lifecycleConditionDto.ConditionTypeOption.IsSet)
    {
        writer.WritePropertyName("conditionType");
        JsonSerializer.Serialize(writer, lifecycleConditionDto.ConditionType, jsonSerializerOptions);
    }
    if (lifecycleConditionDto.RefIdOption.IsSet)
    {
        writer.WritePropertyName("refId");
        JsonSerializer.Serialize(writer, lifecycleConditionDto.RefId, jsonSerializerOptions);
    }
    if (lifecycleConditionDto.RulesOption.IsSet)
    {
        if (lifecycleConditionDto.RulesOption.Value != null)
        {
            writer.WritePropertyName("rules");
            JsonSerializer.Serialize(writer, lifecycleConditionDto.Rules, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("rules");
        }
    }
}

    }
}
