// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// ModuleCollectorOptimizedToursDto
    /// </summary>
    public partial class ModuleCollectorOptimizedToursDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ModuleCollectorOptimizedToursDto" /> class.
        /// </summary>
        /// <param name="skippedShipmentLabels">skippedShipmentLabels</param>
        /// <param name="routes">routes</param>
        [JsonConstructor]
        public ModuleCollectorOptimizedToursDto(Option<List<string>> skippedShipmentLabels = default, Option<List<ModuleCollectorRouteDto>> routes = default)
        {
            SkippedShipmentLabelsOption = skippedShipmentLabels;
            RoutesOption = routes;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SkippedShipmentLabels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>> SkippedShipmentLabelsOption { get; private set; }

        /// <summary>
        /// Gets or Sets SkippedShipmentLabels
        /// </summary>
        [JsonPropertyName("skippedShipmentLabels")]
        public List<string> SkippedShipmentLabels { get { return this.SkippedShipmentLabelsOption; } set { this.SkippedShipmentLabelsOption = new(value); } }

        /// <summary>
        /// Used to track the state of Routes
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<ModuleCollectorRouteDto>> RoutesOption { get; private set; }

        /// <summary>
        /// Gets or Sets Routes
        /// </summary>
        [JsonPropertyName("routes")]
        public List<ModuleCollectorRouteDto> Routes { get { return this.RoutesOption; } set { this.RoutesOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ModuleCollectorOptimizedToursDto {\n");
            sb.Append("  SkippedShipmentLabels: ").Append(SkippedShipmentLabels).Append("\n");
            sb.Append("  Routes: ").Append(Routes).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ModuleCollectorOptimizedToursDto" />
    /// </summary>
    public class ModuleCollectorOptimizedToursDtoJsonConverter : JsonConverter<ModuleCollectorOptimizedToursDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="ModuleCollectorOptimizedToursDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ModuleCollectorOptimizedToursDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<string>> skippedShipmentLabels = default;
            Option<List<ModuleCollectorRouteDto>> routes = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "skippedShipmentLabels":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                skippedShipmentLabels = new Option<List<string>>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "routes":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                routes = new Option<List<ModuleCollectorRouteDto>>(JsonSerializer.Deserialize<List<ModuleCollectorRouteDto>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }


            return new ModuleCollectorOptimizedToursDto(skippedShipmentLabels, routes);
        }

        /// <summary>
        /// Serializes a <see cref="ModuleCollectorOptimizedToursDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="moduleCollectorOptimizedToursDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ModuleCollectorOptimizedToursDto moduleCollectorOptimizedToursDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, moduleCollectorOptimizedToursDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="ModuleCollectorOptimizedToursDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="moduleCollectorOptimizedToursDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, ModuleCollectorOptimizedToursDto moduleCollectorOptimizedToursDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (moduleCollectorOptimizedToursDto.SkippedShipmentLabelsOption.IsSet)
    {
        if (moduleCollectorOptimizedToursDto.SkippedShipmentLabelsOption.Value != null)
        {
            writer.WritePropertyName("skippedShipmentLabels");
            JsonSerializer.Serialize(writer, moduleCollectorOptimizedToursDto.SkippedShipmentLabels, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("skippedShipmentLabels");
        }
    }
    if (moduleCollectorOptimizedToursDto.RoutesOption.IsSet)
    {
        if (moduleCollectorOptimizedToursDto.RoutesOption.Value != null)
        {
            writer.WritePropertyName("routes");
            JsonSerializer.Serialize(writer, moduleCollectorOptimizedToursDto.Routes, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("routes");
        }
    }
}

    }
}
