// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// TenantManagementUpdateCorporateDomainRequestDto
    /// </summary>
    public partial class TenantManagementUpdateCorporateDomainRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantManagementUpdateCorporateDomainRequestDto" /> class.
        /// </summary>
        /// <param name="hostnameId">hostnameId</param>
        /// <param name="domainName">domainName</param>
        /// <param name="certificatePemBase64">certificatePemBase64</param>
        /// <param name="password">password</param>
        /// <param name="acceptsClientCertificate">acceptsClientCertificate</param>
        /// <param name="isSsl">isSsl</param>
        /// <param name="default">default</param>
        /// <param name="port">port</param>
        /// <param name="appId">appId</param>
        [JsonConstructor]
        public TenantManagementUpdateCorporateDomainRequestDto(Option<Guid?> hostnameId = default, Option<string> domainName = default, Option<string> certificatePemBase64 = default, Option<string> password = default, Option<bool?> acceptsClientCertificate = default, Option<bool?> isSsl = default, Option<bool?> @default = default, Option<int?> port = default, Option<Guid?> appId = default)
        {
            HostnameIdOption = hostnameId;
            DomainNameOption = domainName;
            CertificatePemBase64Option = certificatePemBase64;
            PasswordOption = password;
            AcceptsClientCertificateOption = acceptsClientCertificate;
            IsSslOption = isSsl;
            DefaultOption = @default;
            PortOption = port;
            AppIdOption = appId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of HostnameId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> HostnameIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets HostnameId
        /// </summary>
        [JsonPropertyName("hostnameId")]
        public Guid? HostnameId { get { return this.HostnameIdOption; } set { this.HostnameIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of DomainName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> DomainNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets DomainName
        /// </summary>
        [JsonPropertyName("domainName")]
        public string DomainName { get { return this.DomainNameOption; } set { this.DomainNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of CertificatePemBase64
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> CertificatePemBase64Option { get; private set; }

        /// <summary>
        /// Gets or Sets CertificatePemBase64
        /// </summary>
        [JsonPropertyName("certificatePemBase64")]
        public string CertificatePemBase64 { get { return this.CertificatePemBase64Option; } set { this.CertificatePemBase64Option = new(value); } }

        /// <summary>
        /// Used to track the state of Password
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> PasswordOption { get; private set; }

        /// <summary>
        /// Gets or Sets Password
        /// </summary>
        [JsonPropertyName("password")]
        public string Password { get { return this.PasswordOption; } set { this.PasswordOption = new(value); } }

        /// <summary>
        /// Used to track the state of AcceptsClientCertificate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> AcceptsClientCertificateOption { get; private set; }

        /// <summary>
        /// Gets or Sets AcceptsClientCertificate
        /// </summary>
        [JsonPropertyName("acceptsClientCertificate")]
        public bool? AcceptsClientCertificate { get { return this.AcceptsClientCertificateOption; } set { this.AcceptsClientCertificateOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsSsl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsSslOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsSsl
        /// </summary>
        [JsonPropertyName("isSsl")]
        public bool? IsSsl { get { return this.IsSslOption; } set { this.IsSslOption = new(value); } }

        /// <summary>
        /// Used to track the state of Default
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> DefaultOption { get; private set; }

        /// <summary>
        /// Gets or Sets Default
        /// </summary>
        [JsonPropertyName("default")]
        public bool? Default { get { return this.DefaultOption; } set { this.DefaultOption = new(value); } }

        /// <summary>
        /// Used to track the state of Port
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> PortOption { get; private set; }

        /// <summary>
        /// Gets or Sets Port
        /// </summary>
        [JsonPropertyName("port")]
        public int? Port { get { return this.PortOption; } set { this.PortOption = new(value); } }

        /// <summary>
        /// Used to track the state of AppId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> AppIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets AppId
        /// </summary>
        [JsonPropertyName("appId")]
        public Guid? AppId { get { return this.AppIdOption; } set { this.AppIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantManagementUpdateCorporateDomainRequestDto {\n");
            sb.Append("  HostnameId: ").Append(HostnameId).Append("\n");
            sb.Append("  DomainName: ").Append(DomainName).Append("\n");
            sb.Append("  CertificatePemBase64: ").Append(CertificatePemBase64).Append("\n");
            sb.Append("  Password: ").Append(Password).Append("\n");
            sb.Append("  AcceptsClientCertificate: ").Append(AcceptsClientCertificate).Append("\n");
            sb.Append("  IsSsl: ").Append(IsSsl).Append("\n");
            sb.Append("  Default: ").Append(Default).Append("\n");
            sb.Append("  Port: ").Append(Port).Append("\n");
            sb.Append("  AppId: ").Append(AppId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantManagementUpdateCorporateDomainRequestDto" />
    /// </summary>
    public class TenantManagementUpdateCorporateDomainRequestDtoJsonConverter : JsonConverter<TenantManagementUpdateCorporateDomainRequestDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="TenantManagementUpdateCorporateDomainRequestDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TenantManagementUpdateCorporateDomainRequestDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> hostnameId = default;
            Option<string> domainName = default;
            Option<string> certificatePemBase64 = default;
            Option<string> password = default;
            Option<bool?> acceptsClientCertificate = default;
            Option<bool?> isSsl = default;
            Option<bool?> varDefault = default;
            Option<int?> port = default;
            Option<Guid?> appId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "hostnameId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                hostnameId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "domainName":
                            domainName = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "certificatePemBase64":
                            certificatePemBase64 = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "password":
                            password = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "acceptsClientCertificate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                acceptsClientCertificate = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "isSsl":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isSsl = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "default":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                varDefault = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "port":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                port = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "appId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                appId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (hostnameId.IsSet && hostnameId.Value == null)
                throw new ArgumentNullException(nameof(hostnameId), "Property is not nullable for class TenantManagementUpdateCorporateDomainRequestDto.");

            if (acceptsClientCertificate.IsSet && acceptsClientCertificate.Value == null)
                throw new ArgumentNullException(nameof(acceptsClientCertificate), "Property is not nullable for class TenantManagementUpdateCorporateDomainRequestDto.");

            if (isSsl.IsSet && isSsl.Value == null)
                throw new ArgumentNullException(nameof(isSsl), "Property is not nullable for class TenantManagementUpdateCorporateDomainRequestDto.");

            if (varDefault.IsSet && varDefault.Value == null)
                throw new ArgumentNullException(nameof(varDefault), "Property is not nullable for class TenantManagementUpdateCorporateDomainRequestDto.");

            if (port.IsSet && port.Value == null)
                throw new ArgumentNullException(nameof(port), "Property is not nullable for class TenantManagementUpdateCorporateDomainRequestDto.");


            return new TenantManagementUpdateCorporateDomainRequestDto(hostnameId, domainName, certificatePemBase64, password, acceptsClientCertificate, isSsl, varDefault, port, appId);
        }

        /// <summary>
        /// Serializes a <see cref="TenantManagementUpdateCorporateDomainRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantManagementUpdateCorporateDomainRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TenantManagementUpdateCorporateDomainRequestDto tenantManagementUpdateCorporateDomainRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tenantManagementUpdateCorporateDomainRequestDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="TenantManagementUpdateCorporateDomainRequestDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="tenantManagementUpdateCorporateDomainRequestDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, TenantManagementUpdateCorporateDomainRequestDto tenantManagementUpdateCorporateDomainRequestDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (tenantManagementUpdateCorporateDomainRequestDto.HostnameIdOption.IsSet)
    {
        writer.WritePropertyName("hostnameId");
        JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.HostnameId, jsonSerializerOptions);
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.DomainNameOption.IsSet)
    {
        if (tenantManagementUpdateCorporateDomainRequestDto.DomainNameOption.Value != null)
        {
            writer.WritePropertyName("domainName");
            JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.DomainName, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("domainName");
        }
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.CertificatePemBase64Option.IsSet)
    {
        if (tenantManagementUpdateCorporateDomainRequestDto.CertificatePemBase64Option.Value != null)
        {
            writer.WritePropertyName("certificatePemBase64");
            JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.CertificatePemBase64, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("certificatePemBase64");
        }
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.PasswordOption.IsSet)
    {
        if (tenantManagementUpdateCorporateDomainRequestDto.PasswordOption.Value != null)
        {
            writer.WritePropertyName("password");
            JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.Password, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("password");
        }
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.AcceptsClientCertificateOption.IsSet)
    {
        writer.WritePropertyName("acceptsClientCertificate");
        JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.AcceptsClientCertificate, jsonSerializerOptions);
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.IsSslOption.IsSet)
    {
        writer.WritePropertyName("isSsl");
        JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.IsSsl, jsonSerializerOptions);
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.DefaultOption.IsSet)
    {
        writer.WritePropertyName("default");
        JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.Default, jsonSerializerOptions);
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.PortOption.IsSet)
    {
        writer.WritePropertyName("port");
        JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.Port, jsonSerializerOptions);
    }
    if (tenantManagementUpdateCorporateDomainRequestDto.AppIdOption.IsSet)
    {
        if (tenantManagementUpdateCorporateDomainRequestDto.AppIdOption.Value != null)
        {
            writer.WritePropertyName("appId");
            JsonSerializer.Serialize(writer, tenantManagementUpdateCorporateDomainRequestDto.AppId, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("appId");
        }
    }
}

    }
}
