// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// TenantManagementCreateControlDelegationRequestDto
    /// </summary>
    public partial class TenantManagementCreateControlDelegationRequestDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantManagementCreateControlDelegationRequestDto" /> class.
        /// </summary>
        /// <param name="delegatedToUserId">delegatedToUserId</param>
        /// <param name="delegationStartDate">delegationStartDate</param>
        /// <param name="delegationEndDate">delegationEndDate</param>
        /// <param name="reason">reason</param>
        [JsonConstructor]
        public TenantManagementCreateControlDelegationRequestDto(Option<Guid?> delegatedToUserId = default, Option<DateTime?> delegationStartDate = default, Option<DateTime?> delegationEndDate = default, Option<string> reason = default)
        {
            DelegatedToUserIdOption = delegatedToUserId;
            DelegationStartDateOption = delegationStartDate;
            DelegationEndDateOption = delegationEndDate;
            ReasonOption = reason;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of DelegatedToUserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> DelegatedToUserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets DelegatedToUserId
        /// </summary>
        [JsonPropertyName("delegatedToUserId")]
        public Guid? DelegatedToUserId { get { return this.DelegatedToUserIdOption; } set { this.DelegatedToUserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of DelegationStartDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DelegationStartDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets DelegationStartDate
        /// </summary>
        [JsonPropertyName("delegationStartDate")]
        public DateTime? DelegationStartDate { get { return this.DelegationStartDateOption; } set { this.DelegationStartDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of DelegationEndDate
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DelegationEndDateOption { get; private set; }

        /// <summary>
        /// Gets or Sets DelegationEndDate
        /// </summary>
        [JsonPropertyName("delegationEndDate")]
        public DateTime? DelegationEndDate { get { return this.DelegationEndDateOption; } set { this.DelegationEndDateOption = new(value); } }

        /// <summary>
        /// Used to track the state of Reason
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> ReasonOption { get; private set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [JsonPropertyName("reason")]
        public string Reason { get { return this.ReasonOption; } set { this.ReasonOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantManagementCreateControlDelegationRequestDto {\n");
            sb.Append("  DelegatedToUserId: ").Append(DelegatedToUserId).Append("\n");
            sb.Append("  DelegationStartDate: ").Append(DelegationStartDate).Append("\n");
            sb.Append("  DelegationEndDate: ").Append(DelegationEndDate).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantManagementCreateControlDelegationRequestDto" />
    /// </summary>
    public class TenantManagementCreateControlDelegationRequestDtoJsonConverter : JsonConverter<TenantManagementCreateControlDelegationRequestDto>
    {
        /// <summary>
        /// The format to use to serialize DelegationStartDate
        /// </summary>
        public static string DelegationStartDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DelegationEndDate
        /// </summary>
        public static string DelegationEndDateFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="TenantManagementCreateControlDelegationRequestDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TenantManagementCreateControlDelegationRequestDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> delegatedToUserId = default;
            Option<DateTime?> delegationStartDate = default;
            Option<DateTime?> delegationEndDate = default;
            Option<string> reason = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "delegatedToUserId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                delegatedToUserId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "delegationStartDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                delegationStartDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "delegationEndDate":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                delegationEndDate = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime?>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "reason":
                            reason = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (delegatedToUserId.IsSet && delegatedToUserId.Value == null)
                throw new ArgumentNullException(nameof(delegatedToUserId), "Property is not nullable for class TenantManagementCreateControlDelegationRequestDto.");

            if (delegationStartDate.IsSet && delegationStartDate.Value == null)
                throw new ArgumentNullException(nameof(delegationStartDate), "Property is not nullable for class TenantManagementCreateControlDelegationRequestDto.");


            return new TenantManagementCreateControlDelegationRequestDto(delegatedToUserId, delegationStartDate, delegationEndDate, reason);
        }

        /// <summary>
        /// Serializes a <see cref="TenantManagementCreateControlDelegationRequestDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantManagementCreateControlDelegationRequestDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TenantManagementCreateControlDelegationRequestDto tenantManagementCreateControlDelegationRequestDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tenantManagementCreateControlDelegationRequestDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="TenantManagementCreateControlDelegationRequestDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="tenantManagementCreateControlDelegationRequestDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, TenantManagementCreateControlDelegationRequestDto tenantManagementCreateControlDelegationRequestDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (tenantManagementCreateControlDelegationRequestDto.DelegatedToUserIdOption.IsSet)
    {
        writer.WritePropertyName("delegatedToUserId");
        JsonSerializer.Serialize(writer, tenantManagementCreateControlDelegationRequestDto.DelegatedToUserId, jsonSerializerOptions);
    }
    if (tenantManagementCreateControlDelegationRequestDto.DelegationStartDateOption.IsSet)
    {
        writer.WritePropertyName("delegationStartDate");
        JsonSerializer.Serialize(writer, tenantManagementCreateControlDelegationRequestDto.DelegationStartDate, jsonSerializerOptions);
    }
    if (tenantManagementCreateControlDelegationRequestDto.DelegationEndDateOption.IsSet)
    {
        if (tenantManagementCreateControlDelegationRequestDto.DelegationEndDateOption.Value != null)
        {
            writer.WritePropertyName("delegationEndDate");
            JsonSerializer.Serialize(writer, tenantManagementCreateControlDelegationRequestDto.DelegationEndDate, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("delegationEndDate");
        }
    }
    if (tenantManagementCreateControlDelegationRequestDto.ReasonOption.IsSet)
    {
        if (tenantManagementCreateControlDelegationRequestDto.ReasonOption.Value != null)
        {
            writer.WritePropertyName("reason");
            JsonSerializer.Serialize(writer, tenantManagementCreateControlDelegationRequestDto.Reason, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("reason");
        }
    }
}

    }
}
