// <auto-generated>
/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using EleonsoftProxy.Client;

namespace EleonsoftProxy.Model
{
    /// <summary>
    /// TenantManagementCommonTenantExtendedDto
    /// </summary>
    public partial class TenantManagementCommonTenantExtendedDto : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TenantManagementCommonTenantExtendedDto" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="entityVersion">entityVersion</param>
        /// <param name="connectionStrings">connectionStrings</param>
        /// <param name="parentId">parentId</param>
        /// <param name="isRoot">isRoot</param>
        [JsonConstructor]
        public TenantManagementCommonTenantExtendedDto(Option<Guid?> id = default, Option<string> name = default, Option<int?> entityVersion = default, Option<List<TenantManagementTenantConnectionStringDto>> connectionStrings = default, Option<Guid?> parentId = default, Option<bool?> isRoot = default)
        {
            IdOption = id;
            NameOption = name;
            EntityVersionOption = entityVersion;
            ConnectionStringsOption = connectionStrings;
            ParentIdOption = parentId;
            IsRootOption = isRoot;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public Guid? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of EntityVersion
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> EntityVersionOption { get; private set; }

        /// <summary>
        /// Gets or Sets EntityVersion
        /// </summary>
        [JsonPropertyName("entityVersion")]
        public int? EntityVersion { get { return this.EntityVersionOption; } set { this.EntityVersionOption = new(value); } }

        /// <summary>
        /// Used to track the state of ConnectionStrings
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TenantManagementTenantConnectionStringDto>> ConnectionStringsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ConnectionStrings
        /// </summary>
        [JsonPropertyName("connectionStrings")]
        public List<TenantManagementTenantConnectionStringDto> ConnectionStrings { get { return this.ConnectionStringsOption; } set { this.ConnectionStringsOption = new(value); } }

        /// <summary>
        /// Used to track the state of ParentId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Guid?> ParentIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets ParentId
        /// </summary>
        [JsonPropertyName("parentId")]
        public Guid? ParentId { get { return this.ParentIdOption; } set { this.ParentIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of IsRoot
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> IsRootOption { get; private set; }

        /// <summary>
        /// Gets or Sets IsRoot
        /// </summary>
        [JsonPropertyName("isRoot")]
        public bool? IsRoot { get { return this.IsRootOption; } set { this.IsRootOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TenantManagementCommonTenantExtendedDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  EntityVersion: ").Append(EntityVersion).Append("\n");
            sb.Append("  ConnectionStrings: ").Append(ConnectionStrings).Append("\n");
            sb.Append("  ParentId: ").Append(ParentId).Append("\n");
            sb.Append("  IsRoot: ").Append(IsRoot).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TenantManagementCommonTenantExtendedDto" />
    /// </summary>
    public class TenantManagementCommonTenantExtendedDtoJsonConverter : JsonConverter<TenantManagementCommonTenantExtendedDto>
    {
        /// <summary>
        /// Deserializes json to <see cref="TenantManagementCommonTenantExtendedDto" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TenantManagementCommonTenantExtendedDto Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<Guid?> id = default;
            Option<string> name = default;
            Option<int?> entityVersion = default;
            Option<List<TenantManagementTenantConnectionStringDto>> connectionStrings = default;
            Option<Guid?> parentId = default;
            Option<bool?> isRoot = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string localVarJsonPropertyName = utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "name":
                            name = new Option<string>(utf8JsonReader.TokenType == JsonTokenType.Number ? utf8JsonReader.GetInt64().ToString() : utf8JsonReader.GetString());
                            break;
                        case "entityVersion":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                entityVersion = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "connectionStrings":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                connectionStrings = new Option<List<TenantManagementTenantConnectionStringDto>>(JsonSerializer.Deserialize<List<TenantManagementTenantConnectionStringDto>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "parentId":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                parentId = new Option<Guid?>(utf8JsonReader.GetGuid());
                            break;
                        case "isRoot":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                isRoot = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class TenantManagementCommonTenantExtendedDto.");

            if (entityVersion.IsSet && entityVersion.Value == null)
                throw new ArgumentNullException(nameof(entityVersion), "Property is not nullable for class TenantManagementCommonTenantExtendedDto.");

            if (isRoot.IsSet && isRoot.Value == null)
                throw new ArgumentNullException(nameof(isRoot), "Property is not nullable for class TenantManagementCommonTenantExtendedDto.");


            return new TenantManagementCommonTenantExtendedDto(id, name, entityVersion, connectionStrings, parentId, isRoot);
        }

        /// <summary>
        /// Serializes a <see cref="TenantManagementCommonTenantExtendedDto" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="tenantManagementCommonTenantExtendedDto"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TenantManagementCommonTenantExtendedDto tenantManagementCommonTenantExtendedDto, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, tenantManagementCommonTenantExtendedDto, jsonSerializerOptions);
            writer.WriteEndObject();
        }

/// <summary>
/// Serializes the properties of <see cref="TenantManagementCommonTenantExtendedDto" />
/// </summary>
/// <param name="writer"></param>
/// <param name="tenantManagementCommonTenantExtendedDto"></param>
/// <param name="jsonSerializerOptions"></param>
public void WriteProperties(Utf8JsonWriter writer, TenantManagementCommonTenantExtendedDto tenantManagementCommonTenantExtendedDto, JsonSerializerOptions jsonSerializerOptions)
{
    if (tenantManagementCommonTenantExtendedDto.IdOption.IsSet)
    {
        writer.WritePropertyName("id");
        JsonSerializer.Serialize(writer, tenantManagementCommonTenantExtendedDto.Id, jsonSerializerOptions);
    }
    if (tenantManagementCommonTenantExtendedDto.NameOption.IsSet)
    {
        if (tenantManagementCommonTenantExtendedDto.NameOption.Value != null)
        {
            writer.WritePropertyName("name");
            JsonSerializer.Serialize(writer, tenantManagementCommonTenantExtendedDto.Name, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("name");
        }
    }
    if (tenantManagementCommonTenantExtendedDto.EntityVersionOption.IsSet)
    {
        writer.WritePropertyName("entityVersion");
        JsonSerializer.Serialize(writer, tenantManagementCommonTenantExtendedDto.EntityVersion, jsonSerializerOptions);
    }
    if (tenantManagementCommonTenantExtendedDto.ConnectionStringsOption.IsSet)
    {
        if (tenantManagementCommonTenantExtendedDto.ConnectionStringsOption.Value != null)
        {
            writer.WritePropertyName("connectionStrings");
            JsonSerializer.Serialize(writer, tenantManagementCommonTenantExtendedDto.ConnectionStrings, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("connectionStrings");
        }
    }
    if (tenantManagementCommonTenantExtendedDto.ParentIdOption.IsSet)
    {
        if (tenantManagementCommonTenantExtendedDto.ParentIdOption.Value != null)
        {
            writer.WritePropertyName("parentId");
            JsonSerializer.Serialize(writer, tenantManagementCommonTenantExtendedDto.ParentId, jsonSerializerOptions);
        }
        else
        {
            writer.WriteNull("parentId");
        }
    }
    if (tenantManagementCommonTenantExtendedDto.IsRootOption.IsSet)
    {
        writer.WritePropertyName("isRoot");
        JsonSerializer.Serialize(writer, tenantManagementCommonTenantExtendedDto.IsRoot, jsonSerializerOptions);
    }
}

    }
}
