/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing AccountingCreateAccountDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountingCreateAccountDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountingCreateAccountDto
        //private AccountingCreateAccountDto instance;

        public AccountingCreateAccountDtoTests()
        {
            // TODO uncomment below to create an instance of AccountingCreateAccountDto
            //instance = new AccountingCreateAccountDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountingCreateAccountDto
        /// </summary>
        [Fact]
        public void AccountingCreateAccountDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountingCreateAccountDto
            //Assert.IsType<AccountingCreateAccountDto>(instance);
        }

        /// <summary>
        /// Test the property 'DataSourceUid'
        /// </summary>
        [Fact]
        public void DataSourceUidTest()
        {
            // TODO unit test for the property 'DataSourceUid'
        }

        /// <summary>
        /// Test the property 'DataSourceName'
        /// </summary>
        [Fact]
        public void DataSourceNameTest()
        {
            // TODO unit test for the property 'DataSourceName'
        }

        /// <summary>
        /// Test the property 'CompanyUid'
        /// </summary>
        [Fact]
        public void CompanyUidTest()
        {
            // TODO unit test for the property 'CompanyUid'
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'OrganizationUnitId'
        /// </summary>
        [Fact]
        public void OrganizationUnitIdTest()
        {
            // TODO unit test for the property 'OrganizationUnitId'
        }

        /// <summary>
        /// Test the property 'OrganizationUnitName'
        /// </summary>
        [Fact]
        public void OrganizationUnitNameTest()
        {
            // TODO unit test for the property 'OrganizationUnitName'
        }
    }
}
