/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing AccountingAccountDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountingAccountDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountingAccountDto
        //private AccountingAccountDto instance;

        public AccountingAccountDtoTests()
        {
            // TODO uncomment below to create an instance of AccountingAccountDto
            //instance = new AccountingAccountDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountingAccountDto
        /// </summary>
        [Fact]
        public void AccountingAccountDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccountingAccountDto
            //Assert.IsType<AccountingAccountDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'DocEntry'
        /// </summary>
        [Fact]
        public void DocEntryTest()
        {
            // TODO unit test for the property 'DocEntry'
        }

        /// <summary>
        /// Test the property 'DataSourceUid'
        /// </summary>
        [Fact]
        public void DataSourceUidTest()
        {
            // TODO unit test for the property 'DataSourceUid'
        }

        /// <summary>
        /// Test the property 'DataSourceName'
        /// </summary>
        [Fact]
        public void DataSourceNameTest()
        {
            // TODO unit test for the property 'DataSourceName'
        }

        /// <summary>
        /// Test the property 'CompanyUid'
        /// </summary>
        [Fact]
        public void CompanyUidTest()
        {
            // TODO unit test for the property 'CompanyUid'
        }

        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }

        /// <summary>
        /// Test the property 'OrganizationUnitId'
        /// </summary>
        [Fact]
        public void OrganizationUnitIdTest()
        {
            // TODO unit test for the property 'OrganizationUnitId'
        }

        /// <summary>
        /// Test the property 'OrganizationUnitName'
        /// </summary>
        [Fact]
        public void OrganizationUnitNameTest()
        {
            // TODO unit test for the property 'OrganizationUnitName'
        }

        /// <summary>
        /// Test the property 'CurrentBalance'
        /// </summary>
        [Fact]
        public void CurrentBalanceTest()
        {
            // TODO unit test for the property 'CurrentBalance'
        }

        /// <summary>
        /// Test the property 'AccountCurrency'
        /// </summary>
        [Fact]
        public void AccountCurrencyTest()
        {
            // TODO unit test for the property 'AccountCurrency'
        }

        /// <summary>
        /// Test the property 'Invoices'
        /// </summary>
        [Fact]
        public void InvoicesTest()
        {
            // TODO unit test for the property 'Invoices'
        }

        /// <summary>
        /// Test the property 'AccountName'
        /// </summary>
        [Fact]
        public void AccountNameTest()
        {
            // TODO unit test for the property 'AccountName'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'AccountStatus'
        /// </summary>
        [Fact]
        public void AccountStatusTest()
        {
            // TODO unit test for the property 'AccountStatus'
        }

        /// <summary>
        /// Test the property 'DocumentStatus'
        /// </summary>
        [Fact]
        public void DocumentStatusTest()
        {
            // TODO unit test for the property 'DocumentStatus'
        }

        /// <summary>
        /// Test the property 'AccountPackages'
        /// </summary>
        [Fact]
        public void AccountPackagesTest()
        {
            // TODO unit test for the property 'AccountPackages'
        }

        /// <summary>
        /// Test the property 'BillingInformationId'
        /// </summary>
        [Fact]
        public void BillingInformationIdTest()
        {
            // TODO unit test for the property 'BillingInformationId'
        }

        /// <summary>
        /// Test the property 'ResellerRefId'
        /// </summary>
        [Fact]
        public void ResellerRefIdTest()
        {
            // TODO unit test for the property 'ResellerRefId'
        }

        /// <summary>
        /// Test the property 'AccountTenantId'
        /// </summary>
        [Fact]
        public void AccountTenantIdTest()
        {
            // TODO unit test for the property 'AccountTenantId'
        }

        /// <summary>
        /// Test the property 'ResellerType'
        /// </summary>
        [Fact]
        public void ResellerTypeTest()
        {
            // TODO unit test for the property 'ResellerType'
        }

        /// <summary>
        /// Test the property 'CreatorName'
        /// </summary>
        [Fact]
        public void CreatorNameTest()
        {
            // TODO unit test for the property 'CreatorName'
        }

        /// <summary>
        /// Test the property 'CreatorId'
        /// </summary>
        [Fact]
        public void CreatorIdTest()
        {
            // TODO unit test for the property 'CreatorId'
        }

        /// <summary>
        /// Test the property 'BillingInformation'
        /// </summary>
        [Fact]
        public void BillingInformationTest()
        {
            // TODO unit test for the property 'BillingInformation'
        }

        /// <summary>
        /// Test the property 'DocumentVersionEntity'
        /// </summary>
        [Fact]
        public void DocumentVersionEntityTest()
        {
            // TODO unit test for the property 'DocumentVersionEntity'
        }

        /// <summary>
        /// Test the property 'CreationTime'
        /// </summary>
        [Fact]
        public void CreationTimeTest()
        {
            // TODO unit test for the property 'CreationTime'
        }

        /// <summary>
        /// Test the property 'ResellerRefName'
        /// </summary>
        [Fact]
        public void ResellerRefNameTest()
        {
            // TODO unit test for the property 'ResellerRefName'
        }

        /// <summary>
        /// Test the property 'AccountNameEng'
        /// </summary>
        [Fact]
        public void AccountNameEngTest()
        {
            // TODO unit test for the property 'AccountNameEng'
        }

        /// <summary>
        /// Test the property 'AdminEmail'
        /// </summary>
        [Fact]
        public void AdminEmailTest()
        {
            // TODO unit test for the property 'AdminEmail'
        }

        /// <summary>
        /// Test the property 'AdminPassword'
        /// </summary>
        [Fact]
        public void AdminPasswordTest()
        {
            // TODO unit test for the property 'AdminPassword'
        }

        /// <summary>
        /// Test the property 'CreationFromTenant'
        /// </summary>
        [Fact]
        public void CreationFromTenantTest()
        {
            // TODO unit test for the property 'CreationFromTenant'
        }

        /// <summary>
        /// Test the property 'AdminUserName'
        /// </summary>
        [Fact]
        public void AdminUserNameTest()
        {
            // TODO unit test for the property 'AdminUserName'
        }
    }
}
