/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing CollaborationCreateSupportTicketRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CollaborationCreateSupportTicketRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CollaborationCreateSupportTicketRequestDto
        //private CollaborationCreateSupportTicketRequestDto instance;

        public CollaborationCreateSupportTicketRequestDtoTests()
        {
            // TODO uncomment below to create an instance of CollaborationCreateSupportTicketRequestDto
            //instance = new CollaborationCreateSupportTicketRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CollaborationCreateSupportTicketRequestDto
        /// </summary>
        [Fact]
        public void CollaborationCreateSupportTicketRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" CollaborationCreateSupportTicketRequestDto
            //Assert.IsType<CollaborationCreateSupportTicketRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'InitialMembers'
        /// </summary>
        [Fact]
        public void InitialMembersTest()
        {
            // TODO unit test for the property 'InitialMembers'
        }
    }
}
