/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing EleoncoreAuditLogActionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EleoncoreAuditLogActionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EleoncoreAuditLogActionDto
        //private EleoncoreAuditLogActionDto instance;

        public EleoncoreAuditLogActionDtoTests()
        {
            // TODO uncomment below to create an instance of EleoncoreAuditLogActionDto
            //instance = new EleoncoreAuditLogActionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EleoncoreAuditLogActionDto
        /// </summary>
        [Fact]
        public void EleoncoreAuditLogActionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EleoncoreAuditLogActionDto
            //Assert.IsType<EleoncoreAuditLogActionDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'AuditLogId'
        /// </summary>
        [Fact]
        public void AuditLogIdTest()
        {
            // TODO unit test for the property 'AuditLogId'
        }

        /// <summary>
        /// Test the property 'ServiceName'
        /// </summary>
        [Fact]
        public void ServiceNameTest()
        {
            // TODO unit test for the property 'ServiceName'
        }

        /// <summary>
        /// Test the property 'MethodName'
        /// </summary>
        [Fact]
        public void MethodNameTest()
        {
            // TODO unit test for the property 'MethodName'
        }

        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Fact]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }

        /// <summary>
        /// Test the property 'ExecutionTime'
        /// </summary>
        [Fact]
        public void ExecutionTimeTest()
        {
            // TODO unit test for the property 'ExecutionTime'
        }

        /// <summary>
        /// Test the property 'ExecutionDuration'
        /// </summary>
        [Fact]
        public void ExecutionDurationTest()
        {
            // TODO unit test for the property 'ExecutionDuration'
        }
    }
}
