/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing EleoncoreExtensionPropertyApiCreateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EleoncoreExtensionPropertyApiCreateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EleoncoreExtensionPropertyApiCreateDto
        //private EleoncoreExtensionPropertyApiCreateDto instance;

        public EleoncoreExtensionPropertyApiCreateDtoTests()
        {
            // TODO uncomment below to create an instance of EleoncoreExtensionPropertyApiCreateDto
            //instance = new EleoncoreExtensionPropertyApiCreateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EleoncoreExtensionPropertyApiCreateDto
        /// </summary>
        [Fact]
        public void EleoncoreExtensionPropertyApiCreateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EleoncoreExtensionPropertyApiCreateDto
            //Assert.IsType<EleoncoreExtensionPropertyApiCreateDto>(instance);
        }

        /// <summary>
        /// Test the property 'IsAvailable'
        /// </summary>
        [Fact]
        public void IsAvailableTest()
        {
            // TODO unit test for the property 'IsAvailable'
        }
    }
}
