/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing EleoncoreHttpStatusCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EleoncoreHttpStatusCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EleoncoreHttpStatusCode
        //private EleoncoreHttpStatusCode instance;

        public EleoncoreHttpStatusCodeTests()
        {
            // TODO uncomment below to create an instance of EleoncoreHttpStatusCode
            //instance = new EleoncoreHttpStatusCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EleoncoreHttpStatusCode
        /// </summary>
        [Fact]
        public void EleoncoreHttpStatusCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" EleoncoreHttpStatusCode
            //Assert.IsType<EleoncoreHttpStatusCode>(instance);
        }
    }
}
