/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing EleoncoreExtensionPropertyUiFormDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EleoncoreExtensionPropertyUiFormDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EleoncoreExtensionPropertyUiFormDto
        //private EleoncoreExtensionPropertyUiFormDto instance;

        public EleoncoreExtensionPropertyUiFormDtoTests()
        {
            // TODO uncomment below to create an instance of EleoncoreExtensionPropertyUiFormDto
            //instance = new EleoncoreExtensionPropertyUiFormDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EleoncoreExtensionPropertyUiFormDto
        /// </summary>
        [Fact]
        public void EleoncoreExtensionPropertyUiFormDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EleoncoreExtensionPropertyUiFormDto
            //Assert.IsType<EleoncoreExtensionPropertyUiFormDto>(instance);
        }

        /// <summary>
        /// Test the property 'IsVisible'
        /// </summary>
        [Fact]
        public void IsVisibleTest()
        {
            // TODO unit test for the property 'IsVisible'
        }
    }
}
