/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing EleoncoreExtensionPropertyUiDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EleoncoreExtensionPropertyUiDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EleoncoreExtensionPropertyUiDto
        //private EleoncoreExtensionPropertyUiDto instance;

        public EleoncoreExtensionPropertyUiDtoTests()
        {
            // TODO uncomment below to create an instance of EleoncoreExtensionPropertyUiDto
            //instance = new EleoncoreExtensionPropertyUiDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EleoncoreExtensionPropertyUiDto
        /// </summary>
        [Fact]
        public void EleoncoreExtensionPropertyUiDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" EleoncoreExtensionPropertyUiDto
            //Assert.IsType<EleoncoreExtensionPropertyUiDto>(instance);
        }

        /// <summary>
        /// Test the property 'OnTable'
        /// </summary>
        [Fact]
        public void OnTableTest()
        {
            // TODO unit test for the property 'OnTable'
        }

        /// <summary>
        /// Test the property 'OnCreateForm'
        /// </summary>
        [Fact]
        public void OnCreateFormTest()
        {
            // TODO unit test for the property 'OnCreateForm'
        }

        /// <summary>
        /// Test the property 'OnEditForm'
        /// </summary>
        [Fact]
        public void OnEditFormTest()
        {
            // TODO unit test for the property 'OnEditForm'
        }

        /// <summary>
        /// Test the property 'Lookup'
        /// </summary>
        [Fact]
        public void LookupTest()
        {
            // TODO unit test for the property 'Lookup'
        }
    }
}
