/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing LanguageManagementLocalizationResourceDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LanguageManagementLocalizationResourceDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LanguageManagementLocalizationResourceDto
        //private LanguageManagementLocalizationResourceDto instance;

        public LanguageManagementLocalizationResourceDtoTests()
        {
            // TODO uncomment below to create an instance of LanguageManagementLocalizationResourceDto
            //instance = new LanguageManagementLocalizationResourceDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LanguageManagementLocalizationResourceDto
        /// </summary>
        [Fact]
        public void LanguageManagementLocalizationResourceDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" LanguageManagementLocalizationResourceDto
            //Assert.IsType<LanguageManagementLocalizationResourceDto>(instance);
        }

        /// <summary>
        /// Test the property 'ResourceName'
        /// </summary>
        [Fact]
        public void ResourceNameTest()
        {
            // TODO unit test for the property 'ResourceName'
        }

        /// <summary>
        /// Test the property 'Texts'
        /// </summary>
        [Fact]
        public void TextsTest()
        {
            // TODO unit test for the property 'Texts'
        }
    }
}
