/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing LifecycleStatesGroupTemplateDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LifecycleStatesGroupTemplateDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LifecycleStatesGroupTemplateDto
        //private LifecycleStatesGroupTemplateDto instance;

        public LifecycleStatesGroupTemplateDtoTests()
        {
            // TODO uncomment below to create an instance of LifecycleStatesGroupTemplateDto
            //instance = new LifecycleStatesGroupTemplateDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LifecycleStatesGroupTemplateDto
        /// </summary>
        [Fact]
        public void LifecycleStatesGroupTemplateDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" LifecycleStatesGroupTemplateDto
            //Assert.IsType<LifecycleStatesGroupTemplateDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'DocumentObjectType'
        /// </summary>
        [Fact]
        public void DocumentObjectTypeTest()
        {
            // TODO unit test for the property 'DocumentObjectType'
        }

        /// <summary>
        /// Test the property 'GroupName'
        /// </summary>
        [Fact]
        public void GroupNameTest()
        {
            // TODO unit test for the property 'GroupName'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }
    }
}
