/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing ModuleCollectorUpdateChatRequestDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModuleCollectorUpdateChatRequestDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ModuleCollectorUpdateChatRequestDto
        //private ModuleCollectorUpdateChatRequestDto instance;

        public ModuleCollectorUpdateChatRequestDtoTests()
        {
            // TODO uncomment below to create an instance of ModuleCollectorUpdateChatRequestDto
            //instance = new ModuleCollectorUpdateChatRequestDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ModuleCollectorUpdateChatRequestDto
        /// </summary>
        [Fact]
        public void ModuleCollectorUpdateChatRequestDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ModuleCollectorUpdateChatRequestDto
            //Assert.IsType<ModuleCollectorUpdateChatRequestDto>(instance);
        }

        /// <summary>
        /// Test the property 'ChatId'
        /// </summary>
        [Fact]
        public void ChatIdTest()
        {
            // TODO unit test for the property 'ChatId'
        }

        /// <summary>
        /// Test the property 'ChatName'
        /// </summary>
        [Fact]
        public void ChatNameTest()
        {
            // TODO unit test for the property 'ChatName'
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'IsPublic'
        /// </summary>
        [Fact]
        public void IsPublicTest()
        {
            // TODO unit test for the property 'IsPublic'
        }

        /// <summary>
        /// Test the property 'DefaultRole'
        /// </summary>
        [Fact]
        public void DefaultRoleTest()
        {
            // TODO unit test for the property 'DefaultRole'
        }
    }
}
