/*
 * Admin API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using EleonsoftProxy.Model;
using EleonsoftProxy.Client;
using System.Reflection;

namespace EleonsoftProxy.Test.Model
{
    /// <summary>
    ///  Class for testing SharedModuleStorageProviderDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SharedModuleStorageProviderDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SharedModuleStorageProviderDto
        //private SharedModuleStorageProviderDto instance;

        public SharedModuleStorageProviderDtoTests()
        {
            // TODO uncomment below to create an instance of SharedModuleStorageProviderDto
            //instance = new SharedModuleStorageProviderDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SharedModuleStorageProviderDto
        /// </summary>
        [Fact]
        public void SharedModuleStorageProviderDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" SharedModuleStorageProviderDto
            //Assert.IsType<SharedModuleStorageProviderDto>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'IsTested'
        /// </summary>
        [Fact]
        public void IsTestedTest()
        {
            // TODO unit test for the property 'IsTested'
        }

        /// <summary>
        /// Test the property 'FullType'
        /// </summary>
        [Fact]
        public void FullTypeTest()
        {
            // TODO unit test for the property 'FullType'
        }

        /// <summary>
        /// Test the property 'StorageProviderTypeName'
        /// </summary>
        [Fact]
        public void StorageProviderTypeNameTest()
        {
            // TODO unit test for the property 'StorageProviderTypeName'
        }

        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Fact]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }
    }
}
